/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
)

// checks if the AutoTestSearchIncludeApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoTestSearchIncludeApiModel{}

// AutoTestSearchIncludeApiModel struct for AutoTestSearchIncludeApiModel
type AutoTestSearchIncludeApiModel struct {
	// If autotest steps will be included
	IncludeSteps NullableBool `json:"includeSteps,omitempty"`
	// If autotest links will be included
	IncludeLinks NullableBool `json:"includeLinks,omitempty"`
	// If autotest labels will be included
	IncludeLabels NullableBool `json:"includeLabels,omitempty"`
}

// NewAutoTestSearchIncludeApiModel instantiates a new AutoTestSearchIncludeApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoTestSearchIncludeApiModel() *AutoTestSearchIncludeApiModel {
	this := AutoTestSearchIncludeApiModel{}
	return &this
}

// NewAutoTestSearchIncludeApiModelWithDefaults instantiates a new AutoTestSearchIncludeApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoTestSearchIncludeApiModelWithDefaults() *AutoTestSearchIncludeApiModel {
	this := AutoTestSearchIncludeApiModel{}
	return &this
}

// GetIncludeSteps returns the IncludeSteps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AutoTestSearchIncludeApiModel) GetIncludeSteps() bool {
	if o == nil || IsNil(o.IncludeSteps.Get()) {
		var ret bool
		return ret
	}
	return *o.IncludeSteps.Get()
}

// GetIncludeStepsOk returns a tuple with the IncludeSteps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoTestSearchIncludeApiModel) GetIncludeStepsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IncludeSteps.Get(), o.IncludeSteps.IsSet()
}

// HasIncludeSteps returns a boolean if a field has been set.
func (o *AutoTestSearchIncludeApiModel) HasIncludeSteps() bool {
	if o != nil && o.IncludeSteps.IsSet() {
		return true
	}

	return false
}

// SetIncludeSteps gets a reference to the given NullableBool and assigns it to the IncludeSteps field.
func (o *AutoTestSearchIncludeApiModel) SetIncludeSteps(v bool) {
	o.IncludeSteps.Set(&v)
}
// SetIncludeStepsNil sets the value for IncludeSteps to be an explicit nil
func (o *AutoTestSearchIncludeApiModel) SetIncludeStepsNil() {
	o.IncludeSteps.Set(nil)
}

// UnsetIncludeSteps ensures that no value is present for IncludeSteps, not even an explicit nil
func (o *AutoTestSearchIncludeApiModel) UnsetIncludeSteps() {
	o.IncludeSteps.Unset()
}

// GetIncludeLinks returns the IncludeLinks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AutoTestSearchIncludeApiModel) GetIncludeLinks() bool {
	if o == nil || IsNil(o.IncludeLinks.Get()) {
		var ret bool
		return ret
	}
	return *o.IncludeLinks.Get()
}

// GetIncludeLinksOk returns a tuple with the IncludeLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoTestSearchIncludeApiModel) GetIncludeLinksOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IncludeLinks.Get(), o.IncludeLinks.IsSet()
}

// HasIncludeLinks returns a boolean if a field has been set.
func (o *AutoTestSearchIncludeApiModel) HasIncludeLinks() bool {
	if o != nil && o.IncludeLinks.IsSet() {
		return true
	}

	return false
}

// SetIncludeLinks gets a reference to the given NullableBool and assigns it to the IncludeLinks field.
func (o *AutoTestSearchIncludeApiModel) SetIncludeLinks(v bool) {
	o.IncludeLinks.Set(&v)
}
// SetIncludeLinksNil sets the value for IncludeLinks to be an explicit nil
func (o *AutoTestSearchIncludeApiModel) SetIncludeLinksNil() {
	o.IncludeLinks.Set(nil)
}

// UnsetIncludeLinks ensures that no value is present for IncludeLinks, not even an explicit nil
func (o *AutoTestSearchIncludeApiModel) UnsetIncludeLinks() {
	o.IncludeLinks.Unset()
}

// GetIncludeLabels returns the IncludeLabels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AutoTestSearchIncludeApiModel) GetIncludeLabels() bool {
	if o == nil || IsNil(o.IncludeLabels.Get()) {
		var ret bool
		return ret
	}
	return *o.IncludeLabels.Get()
}

// GetIncludeLabelsOk returns a tuple with the IncludeLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoTestSearchIncludeApiModel) GetIncludeLabelsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IncludeLabels.Get(), o.IncludeLabels.IsSet()
}

// HasIncludeLabels returns a boolean if a field has been set.
func (o *AutoTestSearchIncludeApiModel) HasIncludeLabels() bool {
	if o != nil && o.IncludeLabels.IsSet() {
		return true
	}

	return false
}

// SetIncludeLabels gets a reference to the given NullableBool and assigns it to the IncludeLabels field.
func (o *AutoTestSearchIncludeApiModel) SetIncludeLabels(v bool) {
	o.IncludeLabels.Set(&v)
}
// SetIncludeLabelsNil sets the value for IncludeLabels to be an explicit nil
func (o *AutoTestSearchIncludeApiModel) SetIncludeLabelsNil() {
	o.IncludeLabels.Set(nil)
}

// UnsetIncludeLabels ensures that no value is present for IncludeLabels, not even an explicit nil
func (o *AutoTestSearchIncludeApiModel) UnsetIncludeLabels() {
	o.IncludeLabels.Unset()
}

func (o AutoTestSearchIncludeApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoTestSearchIncludeApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.IncludeSteps.IsSet() {
		toSerialize["includeSteps"] = o.IncludeSteps.Get()
	}
	if o.IncludeLinks.IsSet() {
		toSerialize["includeLinks"] = o.IncludeLinks.Get()
	}
	if o.IncludeLabels.IsSet() {
		toSerialize["includeLabels"] = o.IncludeLabels.Get()
	}
	return toSerialize, nil
}

type NullableAutoTestSearchIncludeApiModel struct {
	value *AutoTestSearchIncludeApiModel
	isSet bool
}

func (v NullableAutoTestSearchIncludeApiModel) Get() *AutoTestSearchIncludeApiModel {
	return v.value
}

func (v *NullableAutoTestSearchIncludeApiModel) Set(val *AutoTestSearchIncludeApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoTestSearchIncludeApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoTestSearchIncludeApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoTestSearchIncludeApiModel(val *AutoTestSearchIncludeApiModel) *NullableAutoTestSearchIncludeApiModel {
	return &NullableAutoTestSearchIncludeApiModel{value: val, isSet: true}
}

func (v NullableAutoTestSearchIncludeApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoTestSearchIncludeApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


