/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
)

// checks if the WorkItemExtractionModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkItemExtractionModel{}

// WorkItemExtractionModel Rules for different level entities inclusion/exclusion
type WorkItemExtractionModel struct {
	ProjectIds NullableConfigurationExtractionModelProjectIds `json:"projectIds,omitempty"`
	Ids NullableWorkItemExtractionModelIds `json:"ids,omitempty"`
	SectionIds NullableWorkItemExtractionModelSectionIds `json:"sectionIds,omitempty"`
}

// NewWorkItemExtractionModel instantiates a new WorkItemExtractionModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkItemExtractionModel() *WorkItemExtractionModel {
	this := WorkItemExtractionModel{}
	return &this
}

// NewWorkItemExtractionModelWithDefaults instantiates a new WorkItemExtractionModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkItemExtractionModelWithDefaults() *WorkItemExtractionModel {
	this := WorkItemExtractionModel{}
	return &this
}

// GetProjectIds returns the ProjectIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemExtractionModel) GetProjectIds() ConfigurationExtractionModelProjectIds {
	if o == nil || IsNil(o.ProjectIds.Get()) {
		var ret ConfigurationExtractionModelProjectIds
		return ret
	}
	return *o.ProjectIds.Get()
}

// GetProjectIdsOk returns a tuple with the ProjectIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemExtractionModel) GetProjectIdsOk() (*ConfigurationExtractionModelProjectIds, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectIds.Get(), o.ProjectIds.IsSet()
}

// HasProjectIds returns a boolean if a field has been set.
func (o *WorkItemExtractionModel) HasProjectIds() bool {
	if o != nil && o.ProjectIds.IsSet() {
		return true
	}

	return false
}

// SetProjectIds gets a reference to the given NullableConfigurationExtractionModelProjectIds and assigns it to the ProjectIds field.
func (o *WorkItemExtractionModel) SetProjectIds(v ConfigurationExtractionModelProjectIds) {
	o.ProjectIds.Set(&v)
}
// SetProjectIdsNil sets the value for ProjectIds to be an explicit nil
func (o *WorkItemExtractionModel) SetProjectIdsNil() {
	o.ProjectIds.Set(nil)
}

// UnsetProjectIds ensures that no value is present for ProjectIds, not even an explicit nil
func (o *WorkItemExtractionModel) UnsetProjectIds() {
	o.ProjectIds.Unset()
}

// GetIds returns the Ids field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemExtractionModel) GetIds() WorkItemExtractionModelIds {
	if o == nil || IsNil(o.Ids.Get()) {
		var ret WorkItemExtractionModelIds
		return ret
	}
	return *o.Ids.Get()
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemExtractionModel) GetIdsOk() (*WorkItemExtractionModelIds, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids.Get(), o.Ids.IsSet()
}

// HasIds returns a boolean if a field has been set.
func (o *WorkItemExtractionModel) HasIds() bool {
	if o != nil && o.Ids.IsSet() {
		return true
	}

	return false
}

// SetIds gets a reference to the given NullableWorkItemExtractionModelIds and assigns it to the Ids field.
func (o *WorkItemExtractionModel) SetIds(v WorkItemExtractionModelIds) {
	o.Ids.Set(&v)
}
// SetIdsNil sets the value for Ids to be an explicit nil
func (o *WorkItemExtractionModel) SetIdsNil() {
	o.Ids.Set(nil)
}

// UnsetIds ensures that no value is present for Ids, not even an explicit nil
func (o *WorkItemExtractionModel) UnsetIds() {
	o.Ids.Unset()
}

// GetSectionIds returns the SectionIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemExtractionModel) GetSectionIds() WorkItemExtractionModelSectionIds {
	if o == nil || IsNil(o.SectionIds.Get()) {
		var ret WorkItemExtractionModelSectionIds
		return ret
	}
	return *o.SectionIds.Get()
}

// GetSectionIdsOk returns a tuple with the SectionIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemExtractionModel) GetSectionIdsOk() (*WorkItemExtractionModelSectionIds, bool) {
	if o == nil {
		return nil, false
	}
	return o.SectionIds.Get(), o.SectionIds.IsSet()
}

// HasSectionIds returns a boolean if a field has been set.
func (o *WorkItemExtractionModel) HasSectionIds() bool {
	if o != nil && o.SectionIds.IsSet() {
		return true
	}

	return false
}

// SetSectionIds gets a reference to the given NullableWorkItemExtractionModelSectionIds and assigns it to the SectionIds field.
func (o *WorkItemExtractionModel) SetSectionIds(v WorkItemExtractionModelSectionIds) {
	o.SectionIds.Set(&v)
}
// SetSectionIdsNil sets the value for SectionIds to be an explicit nil
func (o *WorkItemExtractionModel) SetSectionIdsNil() {
	o.SectionIds.Set(nil)
}

// UnsetSectionIds ensures that no value is present for SectionIds, not even an explicit nil
func (o *WorkItemExtractionModel) UnsetSectionIds() {
	o.SectionIds.Unset()
}

func (o WorkItemExtractionModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkItemExtractionModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ProjectIds.IsSet() {
		toSerialize["projectIds"] = o.ProjectIds.Get()
	}
	if o.Ids.IsSet() {
		toSerialize["ids"] = o.Ids.Get()
	}
	if o.SectionIds.IsSet() {
		toSerialize["sectionIds"] = o.SectionIds.Get()
	}
	return toSerialize, nil
}

type NullableWorkItemExtractionModel struct {
	value *WorkItemExtractionModel
	isSet bool
}

func (v NullableWorkItemExtractionModel) Get() *WorkItemExtractionModel {
	return v.value
}

func (v *NullableWorkItemExtractionModel) Set(val *WorkItemExtractionModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkItemExtractionModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkItemExtractionModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkItemExtractionModel(val *WorkItemExtractionModel) *NullableWorkItemExtractionModel {
	return &NullableWorkItemExtractionModel{value: val, isSet: true}
}

func (v NullableWorkItemExtractionModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkItemExtractionModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


