/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
)

// checks if the ParameterPostModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParameterPostModel{}

// ParameterPostModel struct for ParameterPostModel
type ParameterPostModel struct {
	Value string `json:"value"`
	Name string `json:"name"`
}

// NewParameterPostModel instantiates a new ParameterPostModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParameterPostModel(value string, name string) *ParameterPostModel {
	this := ParameterPostModel{}
	this.Value = value
	this.Name = name
	return &this
}

// NewParameterPostModelWithDefaults instantiates a new ParameterPostModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParameterPostModelWithDefaults() *ParameterPostModel {
	this := ParameterPostModel{}
	return &this
}

// GetValue returns the Value field value
func (o *ParameterPostModel) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ParameterPostModel) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ParameterPostModel) SetValue(v string) {
	o.Value = v
}

// GetName returns the Name field value
func (o *ParameterPostModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ParameterPostModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ParameterPostModel) SetName(v string) {
	o.Name = v
}

func (o ParameterPostModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParameterPostModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableParameterPostModel struct {
	value *ParameterPostModel
	isSet bool
}

func (v NullableParameterPostModel) Get() *ParameterPostModel {
	return v.value
}

func (v *NullableParameterPostModel) Set(val *ParameterPostModel) {
	v.value = val
	v.isSet = true
}

func (v NullableParameterPostModel) IsSet() bool {
	return v.isSet
}

func (v *NullableParameterPostModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParameterPostModel(val *ParameterPostModel) *NullableParameterPostModel {
	return &NullableParameterPostModel{value: val, isSet: true}
}

func (v NullableParameterPostModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParameterPostModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


