/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
)

// checks if the Int64RangeSelectorModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Int64RangeSelectorModel{}

// Int64RangeSelectorModel struct for Int64RangeSelectorModel
type Int64RangeSelectorModel struct {
	From NullableInt64 `json:"from,omitempty"`
	To NullableInt64 `json:"to,omitempty"`
}

// NewInt64RangeSelectorModel instantiates a new Int64RangeSelectorModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInt64RangeSelectorModel() *Int64RangeSelectorModel {
	this := Int64RangeSelectorModel{}
	return &this
}

// NewInt64RangeSelectorModelWithDefaults instantiates a new Int64RangeSelectorModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInt64RangeSelectorModelWithDefaults() *Int64RangeSelectorModel {
	this := Int64RangeSelectorModel{}
	return &this
}

// GetFrom returns the From field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Int64RangeSelectorModel) GetFrom() int64 {
	if o == nil || IsNil(o.From.Get()) {
		var ret int64
		return ret
	}
	return *o.From.Get()
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Int64RangeSelectorModel) GetFromOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.From.Get(), o.From.IsSet()
}

// HasFrom returns a boolean if a field has been set.
func (o *Int64RangeSelectorModel) HasFrom() bool {
	if o != nil && o.From.IsSet() {
		return true
	}

	return false
}

// SetFrom gets a reference to the given NullableInt64 and assigns it to the From field.
func (o *Int64RangeSelectorModel) SetFrom(v int64) {
	o.From.Set(&v)
}
// SetFromNil sets the value for From to be an explicit nil
func (o *Int64RangeSelectorModel) SetFromNil() {
	o.From.Set(nil)
}

// UnsetFrom ensures that no value is present for From, not even an explicit nil
func (o *Int64RangeSelectorModel) UnsetFrom() {
	o.From.Unset()
}

// GetTo returns the To field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Int64RangeSelectorModel) GetTo() int64 {
	if o == nil || IsNil(o.To.Get()) {
		var ret int64
		return ret
	}
	return *o.To.Get()
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Int64RangeSelectorModel) GetToOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.To.Get(), o.To.IsSet()
}

// HasTo returns a boolean if a field has been set.
func (o *Int64RangeSelectorModel) HasTo() bool {
	if o != nil && o.To.IsSet() {
		return true
	}

	return false
}

// SetTo gets a reference to the given NullableInt64 and assigns it to the To field.
func (o *Int64RangeSelectorModel) SetTo(v int64) {
	o.To.Set(&v)
}
// SetToNil sets the value for To to be an explicit nil
func (o *Int64RangeSelectorModel) SetToNil() {
	o.To.Set(nil)
}

// UnsetTo ensures that no value is present for To, not even an explicit nil
func (o *Int64RangeSelectorModel) UnsetTo() {
	o.To.Unset()
}

func (o Int64RangeSelectorModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Int64RangeSelectorModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.From.IsSet() {
		toSerialize["from"] = o.From.Get()
	}
	if o.To.IsSet() {
		toSerialize["to"] = o.To.Get()
	}
	return toSerialize, nil
}

type NullableInt64RangeSelectorModel struct {
	value *Int64RangeSelectorModel
	isSet bool
}

func (v NullableInt64RangeSelectorModel) Get() *Int64RangeSelectorModel {
	return v.value
}

func (v *NullableInt64RangeSelectorModel) Set(val *Int64RangeSelectorModel) {
	v.value = val
	v.isSet = true
}

func (v NullableInt64RangeSelectorModel) IsSet() bool {
	return v.isSet
}

func (v *NullableInt64RangeSelectorModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInt64RangeSelectorModel(val *Int64RangeSelectorModel) *NullableInt64RangeSelectorModel {
	return &NullableInt64RangeSelectorModel{value: val, isSet: true}
}

func (v NullableInt64RangeSelectorModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInt64RangeSelectorModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


