/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateWorkflowApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWorkflowApiModel{}

// CreateWorkflowApiModel struct for CreateWorkflowApiModel
type CreateWorkflowApiModel struct {
	Name string `json:"name"`
	IsDefault NullableBool `json:"isDefault,omitempty"`
	Statuses []WorkflowStatusApiModel `json:"statuses"`
	ProjectIds []string `json:"projectIds,omitempty"`
}

type _CreateWorkflowApiModel CreateWorkflowApiModel

// NewCreateWorkflowApiModel instantiates a new CreateWorkflowApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWorkflowApiModel(name string, statuses []WorkflowStatusApiModel) *CreateWorkflowApiModel {
	this := CreateWorkflowApiModel{}
	this.Name = name
	this.Statuses = statuses
	return &this
}

// NewCreateWorkflowApiModelWithDefaults instantiates a new CreateWorkflowApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWorkflowApiModelWithDefaults() *CreateWorkflowApiModel {
	this := CreateWorkflowApiModel{}
	return &this
}

// GetName returns the Name field value
func (o *CreateWorkflowApiModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateWorkflowApiModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateWorkflowApiModel) SetName(v string) {
	o.Name = v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkflowApiModel) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault.Get()) {
		var ret bool
		return ret
	}
	return *o.IsDefault.Get()
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkflowApiModel) GetIsDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsDefault.Get(), o.IsDefault.IsSet()
}

// HasIsDefault returns a boolean if a field has been set.
func (o *CreateWorkflowApiModel) HasIsDefault() bool {
	if o != nil && o.IsDefault.IsSet() {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given NullableBool and assigns it to the IsDefault field.
func (o *CreateWorkflowApiModel) SetIsDefault(v bool) {
	o.IsDefault.Set(&v)
}
// SetIsDefaultNil sets the value for IsDefault to be an explicit nil
func (o *CreateWorkflowApiModel) SetIsDefaultNil() {
	o.IsDefault.Set(nil)
}

// UnsetIsDefault ensures that no value is present for IsDefault, not even an explicit nil
func (o *CreateWorkflowApiModel) UnsetIsDefault() {
	o.IsDefault.Unset()
}

// GetStatuses returns the Statuses field value
func (o *CreateWorkflowApiModel) GetStatuses() []WorkflowStatusApiModel {
	if o == nil {
		var ret []WorkflowStatusApiModel
		return ret
	}

	return o.Statuses
}

// GetStatusesOk returns a tuple with the Statuses field value
// and a boolean to check if the value has been set.
func (o *CreateWorkflowApiModel) GetStatusesOk() ([]WorkflowStatusApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Statuses, true
}

// SetStatuses sets field value
func (o *CreateWorkflowApiModel) SetStatuses(v []WorkflowStatusApiModel) {
	o.Statuses = v
}

// GetProjectIds returns the ProjectIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkflowApiModel) GetProjectIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ProjectIds
}

// GetProjectIdsOk returns a tuple with the ProjectIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkflowApiModel) GetProjectIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ProjectIds) {
		return nil, false
	}
	return o.ProjectIds, true
}

// HasProjectIds returns a boolean if a field has been set.
func (o *CreateWorkflowApiModel) HasProjectIds() bool {
	if o != nil && !IsNil(o.ProjectIds) {
		return true
	}

	return false
}

// SetProjectIds gets a reference to the given []string and assigns it to the ProjectIds field.
func (o *CreateWorkflowApiModel) SetProjectIds(v []string) {
	o.ProjectIds = v
}

func (o CreateWorkflowApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWorkflowApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.IsDefault.IsSet() {
		toSerialize["isDefault"] = o.IsDefault.Get()
	}
	toSerialize["statuses"] = o.Statuses
	if o.ProjectIds != nil {
		toSerialize["projectIds"] = o.ProjectIds
	}
	return toSerialize, nil
}

func (o *CreateWorkflowApiModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"statuses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWorkflowApiModel := _CreateWorkflowApiModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateWorkflowApiModel)

	if err != nil {
		return err
	}

	*o = CreateWorkflowApiModel(varCreateWorkflowApiModel)

	return err
}

type NullableCreateWorkflowApiModel struct {
	value *CreateWorkflowApiModel
	isSet bool
}

func (v NullableCreateWorkflowApiModel) Get() *CreateWorkflowApiModel {
	return v.value
}

func (v *NullableCreateWorkflowApiModel) Set(val *CreateWorkflowApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWorkflowApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWorkflowApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWorkflowApiModel(val *CreateWorkflowApiModel) *NullableCreateWorkflowApiModel {
	return &NullableCreateWorkflowApiModel{value: val, isSet: true}
}

func (v NullableCreateWorkflowApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWorkflowApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


