/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
)

// checks if the TestPlanTestPointsExtractionApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestPlanTestPointsExtractionApiModel{}

// TestPlanTestPointsExtractionApiModel struct for TestPlanTestPointsExtractionApiModel
type TestPlanTestPointsExtractionApiModel struct {
	// Extraction parameters for test points
	Ids NullableGuidExtractionModel `json:"ids,omitempty"`
}

// NewTestPlanTestPointsExtractionApiModel instantiates a new TestPlanTestPointsExtractionApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestPlanTestPointsExtractionApiModel() *TestPlanTestPointsExtractionApiModel {
	this := TestPlanTestPointsExtractionApiModel{}
	return &this
}

// NewTestPlanTestPointsExtractionApiModelWithDefaults instantiates a new TestPlanTestPointsExtractionApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestPlanTestPointsExtractionApiModelWithDefaults() *TestPlanTestPointsExtractionApiModel {
	this := TestPlanTestPointsExtractionApiModel{}
	return &this
}

// GetIds returns the Ids field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TestPlanTestPointsExtractionApiModel) GetIds() GuidExtractionModel {
	if o == nil || IsNil(o.Ids.Get()) {
		var ret GuidExtractionModel
		return ret
	}
	return *o.Ids.Get()
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TestPlanTestPointsExtractionApiModel) GetIdsOk() (*GuidExtractionModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids.Get(), o.Ids.IsSet()
}

// HasIds returns a boolean if a field has been set.
func (o *TestPlanTestPointsExtractionApiModel) HasIds() bool {
	if o != nil && o.Ids.IsSet() {
		return true
	}

	return false
}

// SetIds gets a reference to the given NullableGuidExtractionModel and assigns it to the Ids field.
func (o *TestPlanTestPointsExtractionApiModel) SetIds(v GuidExtractionModel) {
	o.Ids.Set(&v)
}
// SetIdsNil sets the value for Ids to be an explicit nil
func (o *TestPlanTestPointsExtractionApiModel) SetIdsNil() {
	o.Ids.Set(nil)
}

// UnsetIds ensures that no value is present for Ids, not even an explicit nil
func (o *TestPlanTestPointsExtractionApiModel) UnsetIds() {
	o.Ids.Unset()
}

func (o TestPlanTestPointsExtractionApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestPlanTestPointsExtractionApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Ids.IsSet() {
		toSerialize["ids"] = o.Ids.Get()
	}
	return toSerialize, nil
}

type NullableTestPlanTestPointsExtractionApiModel struct {
	value *TestPlanTestPointsExtractionApiModel
	isSet bool
}

func (v NullableTestPlanTestPointsExtractionApiModel) Get() *TestPlanTestPointsExtractionApiModel {
	return v.value
}

func (v *NullableTestPlanTestPointsExtractionApiModel) Set(val *TestPlanTestPointsExtractionApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTestPlanTestPointsExtractionApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTestPlanTestPointsExtractionApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestPlanTestPointsExtractionApiModel(val *TestPlanTestPointsExtractionApiModel) *NullableTestPlanTestPointsExtractionApiModel {
	return &NullableTestPlanTestPointsExtractionApiModel{value: val, isSet: true}
}

func (v NullableTestPlanTestPointsExtractionApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestPlanTestPointsExtractionApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


