/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
)

// checks if the ProjectTestPlansFilterModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectTestPlansFilterModel{}

// ProjectTestPlansFilterModel struct for ProjectTestPlansFilterModel
type ProjectTestPlansFilterModel struct {
	Name NullableString `json:"name,omitempty"`
	Description NullableString `json:"description,omitempty"`
	Build NullableString `json:"build,omitempty"`
	ProductName NullableString `json:"productName,omitempty"`
	Status []TestPlanStatusModel `json:"status,omitempty"`
	GlobalIds []int64 `json:"globalIds,omitempty"`
	IsLocked NullableBool `json:"isLocked,omitempty"`
	LockedDate *DateTimeRangeSelectorModel `json:"lockedDate,omitempty"`
	AutomaticDurationTimer []bool `json:"automaticDurationTimer,omitempty"`
	CreatedByIds []string `json:"createdByIds,omitempty"`
	CreatedDate *DateTimeRangeSelectorModel `json:"createdDate,omitempty"`
	StartDate *DateTimeRangeSelectorModel `json:"startDate,omitempty"`
	EndDate *DateTimeRangeSelectorModel `json:"endDate,omitempty"`
	TagNames []string `json:"tagNames,omitempty"`
	Attributes map[string][]string `json:"attributes,omitempty"`
	IsDeleted NullableBool `json:"isDeleted,omitempty"`
}

// NewProjectTestPlansFilterModel instantiates a new ProjectTestPlansFilterModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectTestPlansFilterModel() *ProjectTestPlansFilterModel {
	this := ProjectTestPlansFilterModel{}
	return &this
}

// NewProjectTestPlansFilterModelWithDefaults instantiates a new ProjectTestPlansFilterModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectTestPlansFilterModelWithDefaults() *ProjectTestPlansFilterModel {
	this := ProjectTestPlansFilterModel{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ProjectTestPlansFilterModel) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *ProjectTestPlansFilterModel) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ProjectTestPlansFilterModel) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ProjectTestPlansFilterModel) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ProjectTestPlansFilterModel) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ProjectTestPlansFilterModel) UnsetDescription() {
	o.Description.Unset()
}

// GetBuild returns the Build field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetBuild() string {
	if o == nil || IsNil(o.Build.Get()) {
		var ret string
		return ret
	}
	return *o.Build.Get()
}

// GetBuildOk returns a tuple with the Build field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetBuildOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Build.Get(), o.Build.IsSet()
}

// HasBuild returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasBuild() bool {
	if o != nil && o.Build.IsSet() {
		return true
	}

	return false
}

// SetBuild gets a reference to the given NullableString and assigns it to the Build field.
func (o *ProjectTestPlansFilterModel) SetBuild(v string) {
	o.Build.Set(&v)
}
// SetBuildNil sets the value for Build to be an explicit nil
func (o *ProjectTestPlansFilterModel) SetBuildNil() {
	o.Build.Set(nil)
}

// UnsetBuild ensures that no value is present for Build, not even an explicit nil
func (o *ProjectTestPlansFilterModel) UnsetBuild() {
	o.Build.Unset()
}

// GetProductName returns the ProductName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetProductName() string {
	if o == nil || IsNil(o.ProductName.Get()) {
		var ret string
		return ret
	}
	return *o.ProductName.Get()
}

// GetProductNameOk returns a tuple with the ProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetProductNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductName.Get(), o.ProductName.IsSet()
}

// HasProductName returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasProductName() bool {
	if o != nil && o.ProductName.IsSet() {
		return true
	}

	return false
}

// SetProductName gets a reference to the given NullableString and assigns it to the ProductName field.
func (o *ProjectTestPlansFilterModel) SetProductName(v string) {
	o.ProductName.Set(&v)
}
// SetProductNameNil sets the value for ProductName to be an explicit nil
func (o *ProjectTestPlansFilterModel) SetProductNameNil() {
	o.ProductName.Set(nil)
}

// UnsetProductName ensures that no value is present for ProductName, not even an explicit nil
func (o *ProjectTestPlansFilterModel) UnsetProductName() {
	o.ProductName.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetStatus() []TestPlanStatusModel {
	if o == nil {
		var ret []TestPlanStatusModel
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetStatusOk() ([]TestPlanStatusModel, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasStatus() bool {
	if o != nil && IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given []TestPlanStatusModel and assigns it to the Status field.
func (o *ProjectTestPlansFilterModel) SetStatus(v []TestPlanStatusModel) {
	o.Status = v
}

// GetGlobalIds returns the GlobalIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetGlobalIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}
	return o.GlobalIds
}

// GetGlobalIdsOk returns a tuple with the GlobalIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetGlobalIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.GlobalIds) {
		return nil, false
	}
	return o.GlobalIds, true
}

// HasGlobalIds returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasGlobalIds() bool {
	if o != nil && IsNil(o.GlobalIds) {
		return true
	}

	return false
}

// SetGlobalIds gets a reference to the given []int64 and assigns it to the GlobalIds field.
func (o *ProjectTestPlansFilterModel) SetGlobalIds(v []int64) {
	o.GlobalIds = v
}

// GetIsLocked returns the IsLocked field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetIsLocked() bool {
	if o == nil || IsNil(o.IsLocked.Get()) {
		var ret bool
		return ret
	}
	return *o.IsLocked.Get()
}

// GetIsLockedOk returns a tuple with the IsLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetIsLockedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsLocked.Get(), o.IsLocked.IsSet()
}

// HasIsLocked returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasIsLocked() bool {
	if o != nil && o.IsLocked.IsSet() {
		return true
	}

	return false
}

// SetIsLocked gets a reference to the given NullableBool and assigns it to the IsLocked field.
func (o *ProjectTestPlansFilterModel) SetIsLocked(v bool) {
	o.IsLocked.Set(&v)
}
// SetIsLockedNil sets the value for IsLocked to be an explicit nil
func (o *ProjectTestPlansFilterModel) SetIsLockedNil() {
	o.IsLocked.Set(nil)
}

// UnsetIsLocked ensures that no value is present for IsLocked, not even an explicit nil
func (o *ProjectTestPlansFilterModel) UnsetIsLocked() {
	o.IsLocked.Unset()
}

// GetLockedDate returns the LockedDate field value if set, zero value otherwise.
func (o *ProjectTestPlansFilterModel) GetLockedDate() DateTimeRangeSelectorModel {
	if o == nil || IsNil(o.LockedDate) {
		var ret DateTimeRangeSelectorModel
		return ret
	}
	return *o.LockedDate
}

// GetLockedDateOk returns a tuple with the LockedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTestPlansFilterModel) GetLockedDateOk() (*DateTimeRangeSelectorModel, bool) {
	if o == nil || IsNil(o.LockedDate) {
		return nil, false
	}
	return o.LockedDate, true
}

// HasLockedDate returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasLockedDate() bool {
	if o != nil && !IsNil(o.LockedDate) {
		return true
	}

	return false
}

// SetLockedDate gets a reference to the given DateTimeRangeSelectorModel and assigns it to the LockedDate field.
func (o *ProjectTestPlansFilterModel) SetLockedDate(v DateTimeRangeSelectorModel) {
	o.LockedDate = &v
}

// GetAutomaticDurationTimer returns the AutomaticDurationTimer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetAutomaticDurationTimer() []bool {
	if o == nil {
		var ret []bool
		return ret
	}
	return o.AutomaticDurationTimer
}

// GetAutomaticDurationTimerOk returns a tuple with the AutomaticDurationTimer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetAutomaticDurationTimerOk() ([]bool, bool) {
	if o == nil || IsNil(o.AutomaticDurationTimer) {
		return nil, false
	}
	return o.AutomaticDurationTimer, true
}

// HasAutomaticDurationTimer returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasAutomaticDurationTimer() bool {
	if o != nil && IsNil(o.AutomaticDurationTimer) {
		return true
	}

	return false
}

// SetAutomaticDurationTimer gets a reference to the given []bool and assigns it to the AutomaticDurationTimer field.
func (o *ProjectTestPlansFilterModel) SetAutomaticDurationTimer(v []bool) {
	o.AutomaticDurationTimer = v
}

// GetCreatedByIds returns the CreatedByIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetCreatedByIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.CreatedByIds
}

// GetCreatedByIdsOk returns a tuple with the CreatedByIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetCreatedByIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.CreatedByIds) {
		return nil, false
	}
	return o.CreatedByIds, true
}

// HasCreatedByIds returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasCreatedByIds() bool {
	if o != nil && IsNil(o.CreatedByIds) {
		return true
	}

	return false
}

// SetCreatedByIds gets a reference to the given []string and assigns it to the CreatedByIds field.
func (o *ProjectTestPlansFilterModel) SetCreatedByIds(v []string) {
	o.CreatedByIds = v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *ProjectTestPlansFilterModel) GetCreatedDate() DateTimeRangeSelectorModel {
	if o == nil || IsNil(o.CreatedDate) {
		var ret DateTimeRangeSelectorModel
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTestPlansFilterModel) GetCreatedDateOk() (*DateTimeRangeSelectorModel, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given DateTimeRangeSelectorModel and assigns it to the CreatedDate field.
func (o *ProjectTestPlansFilterModel) SetCreatedDate(v DateTimeRangeSelectorModel) {
	o.CreatedDate = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *ProjectTestPlansFilterModel) GetStartDate() DateTimeRangeSelectorModel {
	if o == nil || IsNil(o.StartDate) {
		var ret DateTimeRangeSelectorModel
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTestPlansFilterModel) GetStartDateOk() (*DateTimeRangeSelectorModel, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given DateTimeRangeSelectorModel and assigns it to the StartDate field.
func (o *ProjectTestPlansFilterModel) SetStartDate(v DateTimeRangeSelectorModel) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *ProjectTestPlansFilterModel) GetEndDate() DateTimeRangeSelectorModel {
	if o == nil || IsNil(o.EndDate) {
		var ret DateTimeRangeSelectorModel
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectTestPlansFilterModel) GetEndDateOk() (*DateTimeRangeSelectorModel, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given DateTimeRangeSelectorModel and assigns it to the EndDate field.
func (o *ProjectTestPlansFilterModel) SetEndDate(v DateTimeRangeSelectorModel) {
	o.EndDate = &v
}

// GetTagNames returns the TagNames field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetTagNames() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.TagNames
}

// GetTagNamesOk returns a tuple with the TagNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetTagNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.TagNames) {
		return nil, false
	}
	return o.TagNames, true
}

// HasTagNames returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasTagNames() bool {
	if o != nil && IsNil(o.TagNames) {
		return true
	}

	return false
}

// SetTagNames gets a reference to the given []string and assigns it to the TagNames field.
func (o *ProjectTestPlansFilterModel) SetTagNames(v []string) {
	o.TagNames = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetAttributes() map[string][]string {
	if o == nil {
		var ret map[string][]string
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetAttributesOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return &o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasAttributes() bool {
	if o != nil && IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string][]string and assigns it to the Attributes field.
func (o *ProjectTestPlansFilterModel) SetAttributes(v map[string][]string) {
	o.Attributes = v
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectTestPlansFilterModel) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted.Get()) {
		var ret bool
		return ret
	}
	return *o.IsDeleted.Get()
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectTestPlansFilterModel) GetIsDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsDeleted.Get(), o.IsDeleted.IsSet()
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *ProjectTestPlansFilterModel) HasIsDeleted() bool {
	if o != nil && o.IsDeleted.IsSet() {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given NullableBool and assigns it to the IsDeleted field.
func (o *ProjectTestPlansFilterModel) SetIsDeleted(v bool) {
	o.IsDeleted.Set(&v)
}
// SetIsDeletedNil sets the value for IsDeleted to be an explicit nil
func (o *ProjectTestPlansFilterModel) SetIsDeletedNil() {
	o.IsDeleted.Set(nil)
}

// UnsetIsDeleted ensures that no value is present for IsDeleted, not even an explicit nil
func (o *ProjectTestPlansFilterModel) UnsetIsDeleted() {
	o.IsDeleted.Unset()
}

func (o ProjectTestPlansFilterModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectTestPlansFilterModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Build.IsSet() {
		toSerialize["build"] = o.Build.Get()
	}
	if o.ProductName.IsSet() {
		toSerialize["productName"] = o.ProductName.Get()
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.GlobalIds != nil {
		toSerialize["globalIds"] = o.GlobalIds
	}
	if o.IsLocked.IsSet() {
		toSerialize["isLocked"] = o.IsLocked.Get()
	}
	if !IsNil(o.LockedDate) {
		toSerialize["lockedDate"] = o.LockedDate
	}
	if o.AutomaticDurationTimer != nil {
		toSerialize["automaticDurationTimer"] = o.AutomaticDurationTimer
	}
	if o.CreatedByIds != nil {
		toSerialize["createdByIds"] = o.CreatedByIds
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["createdDate"] = o.CreatedDate
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	if o.TagNames != nil {
		toSerialize["tagNames"] = o.TagNames
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if o.IsDeleted.IsSet() {
		toSerialize["isDeleted"] = o.IsDeleted.Get()
	}
	return toSerialize, nil
}

type NullableProjectTestPlansFilterModel struct {
	value *ProjectTestPlansFilterModel
	isSet bool
}

func (v NullableProjectTestPlansFilterModel) Get() *ProjectTestPlansFilterModel {
	return v.value
}

func (v *NullableProjectTestPlansFilterModel) Set(val *ProjectTestPlansFilterModel) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectTestPlansFilterModel) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectTestPlansFilterModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectTestPlansFilterModel(val *ProjectTestPlansFilterModel) *NullableProjectTestPlansFilterModel {
	return &NullableProjectTestPlansFilterModel{value: val, isSet: true}
}

func (v NullableProjectTestPlansFilterModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectTestPlansFilterModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


