/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkItemIdModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkItemIdModel{}

// WorkItemIdModel struct for WorkItemIdModel
type WorkItemIdModel struct {
	// Used for search WorkItem. Internal identifier has a Guid data format. Global identifier has an integer data format
	Id string `json:"id"`
}

type _WorkItemIdModel WorkItemIdModel

// NewWorkItemIdModel instantiates a new WorkItemIdModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkItemIdModel(id string) *WorkItemIdModel {
	this := WorkItemIdModel{}
	this.Id = id
	return &this
}

// NewWorkItemIdModelWithDefaults instantiates a new WorkItemIdModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkItemIdModelWithDefaults() *WorkItemIdModel {
	this := WorkItemIdModel{}
	return &this
}

// GetId returns the Id field value
func (o *WorkItemIdModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkItemIdModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkItemIdModel) SetId(v string) {
	o.Id = v
}

func (o WorkItemIdModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkItemIdModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *WorkItemIdModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkItemIdModel := _WorkItemIdModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkItemIdModel)

	if err != nil {
		return err
	}

	*o = WorkItemIdModel(varWorkItemIdModel)

	return err
}

type NullableWorkItemIdModel struct {
	value *WorkItemIdModel
	isSet bool
}

func (v NullableWorkItemIdModel) Get() *WorkItemIdModel {
	return v.value
}

func (v *NullableWorkItemIdModel) Set(val *WorkItemIdModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkItemIdModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkItemIdModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkItemIdModel(val *WorkItemIdModel) *NullableWorkItemIdModel {
	return &NullableWorkItemIdModel{value: val, isSet: true}
}

func (v NullableWorkItemIdModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkItemIdModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


