/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkItemChangedFieldsViewModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkItemChangedFieldsViewModel{}

// WorkItemChangedFieldsViewModel struct for WorkItemChangedFieldsViewModel
type WorkItemChangedFieldsViewModel struct {
	Name NullableStringChangedFieldWithDiffsViewModel `json:"name,omitempty"`
	IsDeleted BooleanChangedFieldViewModel `json:"isDeleted"`
	ProjectId GuidChangedFieldViewModel `json:"projectId"`
	IsAutomated BooleanChangedFieldViewModel `json:"isAutomated"`
	SectionId GuidChangedFieldViewModel `json:"sectionId"`
	Description NullableStringChangedFieldWithDiffsViewModel `json:"description,omitempty"`
	State StringChangedFieldViewModel `json:"state"`
	Priority StringChangedFieldViewModel `json:"priority"`
	Duration Int32ChangedFieldViewModel `json:"duration"`
	Attributes map[string]WorkItemChangedAttributeViewModel `json:"attributes"`
	Steps WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel `json:"steps"`
	PreconditionSteps WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel `json:"preconditionSteps"`
	PostconditionSteps WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel `json:"postconditionSteps"`
	AutoTests AutoTestChangeViewModelArrayChangedFieldViewModel `json:"autoTests"`
	Attachments AttachmentChangeViewModelArrayChangedFieldViewModel `json:"attachments"`
	Tags StringArrayChangedFieldViewModel `json:"tags"`
	Links WorkItemLinkChangeViewModelArrayChangedFieldViewModel `json:"links"`
	GlobalId Int64ChangedFieldViewModel `json:"globalId"`
	VersionNumber Int32ChangedFieldViewModel `json:"versionNumber"`
	EntityTypeName StringChangedFieldViewModel `json:"entityTypeName"`
}

type _WorkItemChangedFieldsViewModel WorkItemChangedFieldsViewModel

// NewWorkItemChangedFieldsViewModel instantiates a new WorkItemChangedFieldsViewModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkItemChangedFieldsViewModel(isDeleted BooleanChangedFieldViewModel, projectId GuidChangedFieldViewModel, isAutomated BooleanChangedFieldViewModel, sectionId GuidChangedFieldViewModel, state StringChangedFieldViewModel, priority StringChangedFieldViewModel, duration Int32ChangedFieldViewModel, attributes map[string]WorkItemChangedAttributeViewModel, steps WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel, preconditionSteps WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel, postconditionSteps WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel, autoTests AutoTestChangeViewModelArrayChangedFieldViewModel, attachments AttachmentChangeViewModelArrayChangedFieldViewModel, tags StringArrayChangedFieldViewModel, links WorkItemLinkChangeViewModelArrayChangedFieldViewModel, globalId Int64ChangedFieldViewModel, versionNumber Int32ChangedFieldViewModel, entityTypeName StringChangedFieldViewModel) *WorkItemChangedFieldsViewModel {
	this := WorkItemChangedFieldsViewModel{}
	this.IsDeleted = isDeleted
	this.ProjectId = projectId
	this.IsAutomated = isAutomated
	this.SectionId = sectionId
	this.State = state
	this.Priority = priority
	this.Duration = duration
	this.Attributes = attributes
	this.Steps = steps
	this.PreconditionSteps = preconditionSteps
	this.PostconditionSteps = postconditionSteps
	this.AutoTests = autoTests
	this.Attachments = attachments
	this.Tags = tags
	this.Links = links
	this.GlobalId = globalId
	this.VersionNumber = versionNumber
	this.EntityTypeName = entityTypeName
	return &this
}

// NewWorkItemChangedFieldsViewModelWithDefaults instantiates a new WorkItemChangedFieldsViewModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkItemChangedFieldsViewModelWithDefaults() *WorkItemChangedFieldsViewModel {
	this := WorkItemChangedFieldsViewModel{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemChangedFieldsViewModel) GetName() StringChangedFieldWithDiffsViewModel {
	if o == nil || IsNil(o.Name.Get()) {
		var ret StringChangedFieldWithDiffsViewModel
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemChangedFieldsViewModel) GetNameOk() (*StringChangedFieldWithDiffsViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *WorkItemChangedFieldsViewModel) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableStringChangedFieldWithDiffsViewModel and assigns it to the Name field.
func (o *WorkItemChangedFieldsViewModel) SetName(v StringChangedFieldWithDiffsViewModel) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *WorkItemChangedFieldsViewModel) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *WorkItemChangedFieldsViewModel) UnsetName() {
	o.Name.Unset()
}

// GetIsDeleted returns the IsDeleted field value
func (o *WorkItemChangedFieldsViewModel) GetIsDeleted() BooleanChangedFieldViewModel {
	if o == nil {
		var ret BooleanChangedFieldViewModel
		return ret
	}

	return o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetIsDeletedOk() (*BooleanChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDeleted, true
}

// SetIsDeleted sets field value
func (o *WorkItemChangedFieldsViewModel) SetIsDeleted(v BooleanChangedFieldViewModel) {
	o.IsDeleted = v
}

// GetProjectId returns the ProjectId field value
func (o *WorkItemChangedFieldsViewModel) GetProjectId() GuidChangedFieldViewModel {
	if o == nil {
		var ret GuidChangedFieldViewModel
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetProjectIdOk() (*GuidChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *WorkItemChangedFieldsViewModel) SetProjectId(v GuidChangedFieldViewModel) {
	o.ProjectId = v
}

// GetIsAutomated returns the IsAutomated field value
func (o *WorkItemChangedFieldsViewModel) GetIsAutomated() BooleanChangedFieldViewModel {
	if o == nil {
		var ret BooleanChangedFieldViewModel
		return ret
	}

	return o.IsAutomated
}

// GetIsAutomatedOk returns a tuple with the IsAutomated field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetIsAutomatedOk() (*BooleanChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsAutomated, true
}

// SetIsAutomated sets field value
func (o *WorkItemChangedFieldsViewModel) SetIsAutomated(v BooleanChangedFieldViewModel) {
	o.IsAutomated = v
}

// GetSectionId returns the SectionId field value
func (o *WorkItemChangedFieldsViewModel) GetSectionId() GuidChangedFieldViewModel {
	if o == nil {
		var ret GuidChangedFieldViewModel
		return ret
	}

	return o.SectionId
}

// GetSectionIdOk returns a tuple with the SectionId field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetSectionIdOk() (*GuidChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SectionId, true
}

// SetSectionId sets field value
func (o *WorkItemChangedFieldsViewModel) SetSectionId(v GuidChangedFieldViewModel) {
	o.SectionId = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemChangedFieldsViewModel) GetDescription() StringChangedFieldWithDiffsViewModel {
	if o == nil || IsNil(o.Description.Get()) {
		var ret StringChangedFieldWithDiffsViewModel
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemChangedFieldsViewModel) GetDescriptionOk() (*StringChangedFieldWithDiffsViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *WorkItemChangedFieldsViewModel) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableStringChangedFieldWithDiffsViewModel and assigns it to the Description field.
func (o *WorkItemChangedFieldsViewModel) SetDescription(v StringChangedFieldWithDiffsViewModel) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *WorkItemChangedFieldsViewModel) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *WorkItemChangedFieldsViewModel) UnsetDescription() {
	o.Description.Unset()
}

// GetState returns the State field value
func (o *WorkItemChangedFieldsViewModel) GetState() StringChangedFieldViewModel {
	if o == nil {
		var ret StringChangedFieldViewModel
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetStateOk() (*StringChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *WorkItemChangedFieldsViewModel) SetState(v StringChangedFieldViewModel) {
	o.State = v
}

// GetPriority returns the Priority field value
func (o *WorkItemChangedFieldsViewModel) GetPriority() StringChangedFieldViewModel {
	if o == nil {
		var ret StringChangedFieldViewModel
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetPriorityOk() (*StringChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *WorkItemChangedFieldsViewModel) SetPriority(v StringChangedFieldViewModel) {
	o.Priority = v
}

// GetDuration returns the Duration field value
func (o *WorkItemChangedFieldsViewModel) GetDuration() Int32ChangedFieldViewModel {
	if o == nil {
		var ret Int32ChangedFieldViewModel
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetDurationOk() (*Int32ChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *WorkItemChangedFieldsViewModel) SetDuration(v Int32ChangedFieldViewModel) {
	o.Duration = v
}

// GetAttributes returns the Attributes field value
func (o *WorkItemChangedFieldsViewModel) GetAttributes() map[string]WorkItemChangedAttributeViewModel {
	if o == nil {
		var ret map[string]WorkItemChangedAttributeViewModel
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetAttributesOk() (*map[string]WorkItemChangedAttributeViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *WorkItemChangedFieldsViewModel) SetAttributes(v map[string]WorkItemChangedAttributeViewModel) {
	o.Attributes = v
}

// GetSteps returns the Steps field value
func (o *WorkItemChangedFieldsViewModel) GetSteps() WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel {
	if o == nil {
		var ret WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetStepsOk() (*WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Steps, true
}

// SetSteps sets field value
func (o *WorkItemChangedFieldsViewModel) SetSteps(v WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel) {
	o.Steps = v
}

// GetPreconditionSteps returns the PreconditionSteps field value
func (o *WorkItemChangedFieldsViewModel) GetPreconditionSteps() WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel {
	if o == nil {
		var ret WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel
		return ret
	}

	return o.PreconditionSteps
}

// GetPreconditionStepsOk returns a tuple with the PreconditionSteps field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetPreconditionStepsOk() (*WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreconditionSteps, true
}

// SetPreconditionSteps sets field value
func (o *WorkItemChangedFieldsViewModel) SetPreconditionSteps(v WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel) {
	o.PreconditionSteps = v
}

// GetPostconditionSteps returns the PostconditionSteps field value
func (o *WorkItemChangedFieldsViewModel) GetPostconditionSteps() WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel {
	if o == nil {
		var ret WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel
		return ret
	}

	return o.PostconditionSteps
}

// GetPostconditionStepsOk returns a tuple with the PostconditionSteps field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetPostconditionStepsOk() (*WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostconditionSteps, true
}

// SetPostconditionSteps sets field value
func (o *WorkItemChangedFieldsViewModel) SetPostconditionSteps(v WorkItemStepChangeViewModelArrayChangedFieldWithDiffsViewModel) {
	o.PostconditionSteps = v
}

// GetAutoTests returns the AutoTests field value
func (o *WorkItemChangedFieldsViewModel) GetAutoTests() AutoTestChangeViewModelArrayChangedFieldViewModel {
	if o == nil {
		var ret AutoTestChangeViewModelArrayChangedFieldViewModel
		return ret
	}

	return o.AutoTests
}

// GetAutoTestsOk returns a tuple with the AutoTests field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetAutoTestsOk() (*AutoTestChangeViewModelArrayChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutoTests, true
}

// SetAutoTests sets field value
func (o *WorkItemChangedFieldsViewModel) SetAutoTests(v AutoTestChangeViewModelArrayChangedFieldViewModel) {
	o.AutoTests = v
}

// GetAttachments returns the Attachments field value
func (o *WorkItemChangedFieldsViewModel) GetAttachments() AttachmentChangeViewModelArrayChangedFieldViewModel {
	if o == nil {
		var ret AttachmentChangeViewModelArrayChangedFieldViewModel
		return ret
	}

	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetAttachmentsOk() (*AttachmentChangeViewModelArrayChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attachments, true
}

// SetAttachments sets field value
func (o *WorkItemChangedFieldsViewModel) SetAttachments(v AttachmentChangeViewModelArrayChangedFieldViewModel) {
	o.Attachments = v
}

// GetTags returns the Tags field value
func (o *WorkItemChangedFieldsViewModel) GetTags() StringArrayChangedFieldViewModel {
	if o == nil {
		var ret StringArrayChangedFieldViewModel
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetTagsOk() (*StringArrayChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tags, true
}

// SetTags sets field value
func (o *WorkItemChangedFieldsViewModel) SetTags(v StringArrayChangedFieldViewModel) {
	o.Tags = v
}

// GetLinks returns the Links field value
func (o *WorkItemChangedFieldsViewModel) GetLinks() WorkItemLinkChangeViewModelArrayChangedFieldViewModel {
	if o == nil {
		var ret WorkItemLinkChangeViewModelArrayChangedFieldViewModel
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetLinksOk() (*WorkItemLinkChangeViewModelArrayChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *WorkItemChangedFieldsViewModel) SetLinks(v WorkItemLinkChangeViewModelArrayChangedFieldViewModel) {
	o.Links = v
}

// GetGlobalId returns the GlobalId field value
func (o *WorkItemChangedFieldsViewModel) GetGlobalId() Int64ChangedFieldViewModel {
	if o == nil {
		var ret Int64ChangedFieldViewModel
		return ret
	}

	return o.GlobalId
}

// GetGlobalIdOk returns a tuple with the GlobalId field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetGlobalIdOk() (*Int64ChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GlobalId, true
}

// SetGlobalId sets field value
func (o *WorkItemChangedFieldsViewModel) SetGlobalId(v Int64ChangedFieldViewModel) {
	o.GlobalId = v
}

// GetVersionNumber returns the VersionNumber field value
func (o *WorkItemChangedFieldsViewModel) GetVersionNumber() Int32ChangedFieldViewModel {
	if o == nil {
		var ret Int32ChangedFieldViewModel
		return ret
	}

	return o.VersionNumber
}

// GetVersionNumberOk returns a tuple with the VersionNumber field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetVersionNumberOk() (*Int32ChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionNumber, true
}

// SetVersionNumber sets field value
func (o *WorkItemChangedFieldsViewModel) SetVersionNumber(v Int32ChangedFieldViewModel) {
	o.VersionNumber = v
}

// GetEntityTypeName returns the EntityTypeName field value
func (o *WorkItemChangedFieldsViewModel) GetEntityTypeName() StringChangedFieldViewModel {
	if o == nil {
		var ret StringChangedFieldViewModel
		return ret
	}

	return o.EntityTypeName
}

// GetEntityTypeNameOk returns a tuple with the EntityTypeName field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModel) GetEntityTypeNameOk() (*StringChangedFieldViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityTypeName, true
}

// SetEntityTypeName sets field value
func (o *WorkItemChangedFieldsViewModel) SetEntityTypeName(v StringChangedFieldViewModel) {
	o.EntityTypeName = v
}

func (o WorkItemChangedFieldsViewModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkItemChangedFieldsViewModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	toSerialize["isDeleted"] = o.IsDeleted
	toSerialize["projectId"] = o.ProjectId
	toSerialize["isAutomated"] = o.IsAutomated
	toSerialize["sectionId"] = o.SectionId
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["state"] = o.State
	toSerialize["priority"] = o.Priority
	toSerialize["duration"] = o.Duration
	toSerialize["attributes"] = o.Attributes
	toSerialize["steps"] = o.Steps
	toSerialize["preconditionSteps"] = o.PreconditionSteps
	toSerialize["postconditionSteps"] = o.PostconditionSteps
	toSerialize["autoTests"] = o.AutoTests
	toSerialize["attachments"] = o.Attachments
	toSerialize["tags"] = o.Tags
	toSerialize["links"] = o.Links
	toSerialize["globalId"] = o.GlobalId
	toSerialize["versionNumber"] = o.VersionNumber
	toSerialize["entityTypeName"] = o.EntityTypeName
	return toSerialize, nil
}

func (o *WorkItemChangedFieldsViewModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isDeleted",
		"projectId",
		"isAutomated",
		"sectionId",
		"state",
		"priority",
		"duration",
		"attributes",
		"steps",
		"preconditionSteps",
		"postconditionSteps",
		"autoTests",
		"attachments",
		"tags",
		"links",
		"globalId",
		"versionNumber",
		"entityTypeName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkItemChangedFieldsViewModel := _WorkItemChangedFieldsViewModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkItemChangedFieldsViewModel)

	if err != nil {
		return err
	}

	*o = WorkItemChangedFieldsViewModel(varWorkItemChangedFieldsViewModel)

	return err
}

type NullableWorkItemChangedFieldsViewModel struct {
	value *WorkItemChangedFieldsViewModel
	isSet bool
}

func (v NullableWorkItemChangedFieldsViewModel) Get() *WorkItemChangedFieldsViewModel {
	return v.value
}

func (v *NullableWorkItemChangedFieldsViewModel) Set(val *WorkItemChangedFieldsViewModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkItemChangedFieldsViewModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkItemChangedFieldsViewModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkItemChangedFieldsViewModel(val *WorkItemChangedFieldsViewModel) *NullableWorkItemChangedFieldsViewModel {
	return &NullableWorkItemChangedFieldsViewModel{value: val, isSet: true}
}

func (v NullableWorkItemChangedFieldsViewModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkItemChangedFieldsViewModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


