/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
)

// checks if the ApiV2WorkItemsCommentsPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV2WorkItemsCommentsPutRequest{}

// ApiV2WorkItemsCommentsPutRequest struct for ApiV2WorkItemsCommentsPutRequest
type ApiV2WorkItemsCommentsPutRequest struct {
	// Text of the comment
	Text string `json:"text"`
	// Unique ID of the comment
	Id string `json:"id"`
}

// NewApiV2WorkItemsCommentsPutRequest instantiates a new ApiV2WorkItemsCommentsPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV2WorkItemsCommentsPutRequest(text string, id string) *ApiV2WorkItemsCommentsPutRequest {
	this := ApiV2WorkItemsCommentsPutRequest{}
	this.Text = text
	this.Id = id
	return &this
}

// NewApiV2WorkItemsCommentsPutRequestWithDefaults instantiates a new ApiV2WorkItemsCommentsPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV2WorkItemsCommentsPutRequestWithDefaults() *ApiV2WorkItemsCommentsPutRequest {
	this := ApiV2WorkItemsCommentsPutRequest{}
	return &this
}

// GetText returns the Text field value
func (o *ApiV2WorkItemsCommentsPutRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *ApiV2WorkItemsCommentsPutRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *ApiV2WorkItemsCommentsPutRequest) SetText(v string) {
	o.Text = v
}

// GetId returns the Id field value
func (o *ApiV2WorkItemsCommentsPutRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApiV2WorkItemsCommentsPutRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiV2WorkItemsCommentsPutRequest) SetId(v string) {
	o.Id = v
}

func (o ApiV2WorkItemsCommentsPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV2WorkItemsCommentsPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableApiV2WorkItemsCommentsPutRequest struct {
	value *ApiV2WorkItemsCommentsPutRequest
	isSet bool
}

func (v NullableApiV2WorkItemsCommentsPutRequest) Get() *ApiV2WorkItemsCommentsPutRequest {
	return v.value
}

func (v *NullableApiV2WorkItemsCommentsPutRequest) Set(val *ApiV2WorkItemsCommentsPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV2WorkItemsCommentsPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV2WorkItemsCommentsPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV2WorkItemsCommentsPutRequest(val *ApiV2WorkItemsCommentsPutRequest) *NullableApiV2WorkItemsCommentsPutRequest {
	return &NullableApiV2WorkItemsCommentsPutRequest{value: val, isSet: true}
}

func (v NullableApiV2WorkItemsCommentsPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV2WorkItemsCommentsPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


