/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FieldFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldFilter{}

// FieldFilter struct for FieldFilter
type FieldFilter struct {
	Operator FilterOperator `json:"operator"`
	Value NullableString `json:"value"`
}

type _FieldFilter FieldFilter

// NewFieldFilter instantiates a new FieldFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldFilter(operator FilterOperator, value NullableString) *FieldFilter {
	this := FieldFilter{}
	this.Operator = operator
	this.Value = value
	return &this
}

// NewFieldFilterWithDefaults instantiates a new FieldFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldFilterWithDefaults() *FieldFilter {
	this := FieldFilter{}
	return &this
}

// GetOperator returns the Operator field value
func (o *FieldFilter) GetOperator() FilterOperator {
	if o == nil {
		var ret FilterOperator
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *FieldFilter) GetOperatorOk() (*FilterOperator, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *FieldFilter) SetOperator(v FilterOperator) {
	o.Operator = v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FieldFilter) GetValue() string {
	if o == nil || o.Value.Get() == nil {
		var ret string
		return ret
	}

	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FieldFilter) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// SetValue sets field value
func (o *FieldFilter) SetValue(v string) {
	o.Value.Set(&v)
}

func (o FieldFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operator"] = o.Operator
	toSerialize["value"] = o.Value.Get()
	return toSerialize, nil
}

func (o *FieldFilter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operator",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFieldFilter := _FieldFilter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFieldFilter)

	if err != nil {
		return err
	}

	*o = FieldFilter(varFieldFilter)

	return err
}

type NullableFieldFilter struct {
	value *FieldFilter
	isSet bool
}

func (v NullableFieldFilter) Get() *FieldFilter {
	return v.value
}

func (v *NullableFieldFilter) Set(val *FieldFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldFilter(val *FieldFilter) *NullableFieldFilter {
	return &NullableFieldFilter{value: val, isSet: true}
}

func (v NullableFieldFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


