/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
)

// checks if the TestPointChangeViewModelChangedFieldViewModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestPointChangeViewModelChangedFieldViewModel{}

// TestPointChangeViewModelChangedFieldViewModel struct for TestPointChangeViewModelChangedFieldViewModel
type TestPointChangeViewModelChangedFieldViewModel struct {
	OldValue NullableTestPointChangeViewModel `json:"oldValue,omitempty"`
	NewValue NullableTestPointChangeViewModel `json:"newValue,omitempty"`
}

// NewTestPointChangeViewModelChangedFieldViewModel instantiates a new TestPointChangeViewModelChangedFieldViewModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestPointChangeViewModelChangedFieldViewModel() *TestPointChangeViewModelChangedFieldViewModel {
	this := TestPointChangeViewModelChangedFieldViewModel{}
	return &this
}

// NewTestPointChangeViewModelChangedFieldViewModelWithDefaults instantiates a new TestPointChangeViewModelChangedFieldViewModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestPointChangeViewModelChangedFieldViewModelWithDefaults() *TestPointChangeViewModelChangedFieldViewModel {
	this := TestPointChangeViewModelChangedFieldViewModel{}
	return &this
}

// GetOldValue returns the OldValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TestPointChangeViewModelChangedFieldViewModel) GetOldValue() TestPointChangeViewModel {
	if o == nil || IsNil(o.OldValue.Get()) {
		var ret TestPointChangeViewModel
		return ret
	}
	return *o.OldValue.Get()
}

// GetOldValueOk returns a tuple with the OldValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TestPointChangeViewModelChangedFieldViewModel) GetOldValueOk() (*TestPointChangeViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.OldValue.Get(), o.OldValue.IsSet()
}

// HasOldValue returns a boolean if a field has been set.
func (o *TestPointChangeViewModelChangedFieldViewModel) HasOldValue() bool {
	if o != nil && o.OldValue.IsSet() {
		return true
	}

	return false
}

// SetOldValue gets a reference to the given NullableTestPointChangeViewModel and assigns it to the OldValue field.
func (o *TestPointChangeViewModelChangedFieldViewModel) SetOldValue(v TestPointChangeViewModel) {
	o.OldValue.Set(&v)
}
// SetOldValueNil sets the value for OldValue to be an explicit nil
func (o *TestPointChangeViewModelChangedFieldViewModel) SetOldValueNil() {
	o.OldValue.Set(nil)
}

// UnsetOldValue ensures that no value is present for OldValue, not even an explicit nil
func (o *TestPointChangeViewModelChangedFieldViewModel) UnsetOldValue() {
	o.OldValue.Unset()
}

// GetNewValue returns the NewValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TestPointChangeViewModelChangedFieldViewModel) GetNewValue() TestPointChangeViewModel {
	if o == nil || IsNil(o.NewValue.Get()) {
		var ret TestPointChangeViewModel
		return ret
	}
	return *o.NewValue.Get()
}

// GetNewValueOk returns a tuple with the NewValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TestPointChangeViewModelChangedFieldViewModel) GetNewValueOk() (*TestPointChangeViewModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.NewValue.Get(), o.NewValue.IsSet()
}

// HasNewValue returns a boolean if a field has been set.
func (o *TestPointChangeViewModelChangedFieldViewModel) HasNewValue() bool {
	if o != nil && o.NewValue.IsSet() {
		return true
	}

	return false
}

// SetNewValue gets a reference to the given NullableTestPointChangeViewModel and assigns it to the NewValue field.
func (o *TestPointChangeViewModelChangedFieldViewModel) SetNewValue(v TestPointChangeViewModel) {
	o.NewValue.Set(&v)
}
// SetNewValueNil sets the value for NewValue to be an explicit nil
func (o *TestPointChangeViewModelChangedFieldViewModel) SetNewValueNil() {
	o.NewValue.Set(nil)
}

// UnsetNewValue ensures that no value is present for NewValue, not even an explicit nil
func (o *TestPointChangeViewModelChangedFieldViewModel) UnsetNewValue() {
	o.NewValue.Unset()
}

func (o TestPointChangeViewModelChangedFieldViewModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestPointChangeViewModelChangedFieldViewModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.OldValue.IsSet() {
		toSerialize["oldValue"] = o.OldValue.Get()
	}
	if o.NewValue.IsSet() {
		toSerialize["newValue"] = o.NewValue.Get()
	}
	return toSerialize, nil
}

type NullableTestPointChangeViewModelChangedFieldViewModel struct {
	value *TestPointChangeViewModelChangedFieldViewModel
	isSet bool
}

func (v NullableTestPointChangeViewModelChangedFieldViewModel) Get() *TestPointChangeViewModelChangedFieldViewModel {
	return v.value
}

func (v *NullableTestPointChangeViewModelChangedFieldViewModel) Set(val *TestPointChangeViewModelChangedFieldViewModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTestPointChangeViewModelChangedFieldViewModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTestPointChangeViewModelChangedFieldViewModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestPointChangeViewModelChangedFieldViewModel(val *TestPointChangeViewModelChangedFieldViewModel) *NullableTestPointChangeViewModelChangedFieldViewModel {
	return &NullableTestPointChangeViewModelChangedFieldViewModel{value: val, isSet: true}
}

func (v NullableTestPointChangeViewModelChangedFieldViewModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestPointChangeViewModelChangedFieldViewModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


