/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"fmt"
)

// TestPlanStatusModel the model 'TestPlanStatusModel'
type TestPlanStatusModel string

// List of TestPlanStatusModel
const (
	TESTPLANSTATUSMODEL_NEW TestPlanStatusModel = "New"
	TESTPLANSTATUSMODEL_IN_PROGRESS TestPlanStatusModel = "InProgress"
	TESTPLANSTATUSMODEL_PAUSED TestPlanStatusModel = "Paused"
	TESTPLANSTATUSMODEL_COMPLETED TestPlanStatusModel = "Completed"
)

// All allowed values of TestPlanStatusModel enum
var AllowedTestPlanStatusModelEnumValues = []TestPlanStatusModel{
	"New",
	"InProgress",
	"Paused",
	"Completed",
}

func (v *TestPlanStatusModel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TestPlanStatusModel(value)
	for _, existing := range AllowedTestPlanStatusModelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TestPlanStatusModel", value)
}

// NewTestPlanStatusModelFromValue returns a pointer to a valid TestPlanStatusModel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTestPlanStatusModelFromValue(v string) (*TestPlanStatusModel, error) {
	ev := TestPlanStatusModel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TestPlanStatusModel: valid values are %v", v, AllowedTestPlanStatusModelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TestPlanStatusModel) IsValid() bool {
	for _, existing := range AllowedTestPlanStatusModelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TestPlanStatusModel value
func (v TestPlanStatusModel) Ptr() *TestPlanStatusModel {
	return &v
}

type NullableTestPlanStatusModel struct {
	value *TestPlanStatusModel
	isSet bool
}

func (v NullableTestPlanStatusModel) Get() *TestPlanStatusModel {
	return v.value
}

func (v *NullableTestPlanStatusModel) Set(val *TestPlanStatusModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTestPlanStatusModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTestPlanStatusModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestPlanStatusModel(val *TestPlanStatusModel) *NullableTestPlanStatusModel {
	return &NullableTestPlanStatusModel{value: val, isSet: true}
}

func (v NullableTestPlanStatusModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestPlanStatusModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

