/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateFailureCategoryProjectApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateFailureCategoryProjectApiModel{}

// UpdateFailureCategoryProjectApiModel struct for UpdateFailureCategoryProjectApiModel
type UpdateFailureCategoryProjectApiModel struct {
	// Failure category identifier
	Id string `json:"id"`
	// Failure category name
	Name string `json:"name"`
	// Category type
	FailureCategory FailureCategory `json:"failureCategory"`
	// Failure category regexes
	FailureClassRegexes []UpdateFailureClassRegexApiModel `json:"failureClassRegexes,omitempty"`
}

type _UpdateFailureCategoryProjectApiModel UpdateFailureCategoryProjectApiModel

// NewUpdateFailureCategoryProjectApiModel instantiates a new UpdateFailureCategoryProjectApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateFailureCategoryProjectApiModel(id string, name string, failureCategory FailureCategory) *UpdateFailureCategoryProjectApiModel {
	this := UpdateFailureCategoryProjectApiModel{}
	this.Id = id
	this.Name = name
	this.FailureCategory = failureCategory
	return &this
}

// NewUpdateFailureCategoryProjectApiModelWithDefaults instantiates a new UpdateFailureCategoryProjectApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateFailureCategoryProjectApiModelWithDefaults() *UpdateFailureCategoryProjectApiModel {
	this := UpdateFailureCategoryProjectApiModel{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateFailureCategoryProjectApiModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateFailureCategoryProjectApiModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateFailureCategoryProjectApiModel) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *UpdateFailureCategoryProjectApiModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateFailureCategoryProjectApiModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateFailureCategoryProjectApiModel) SetName(v string) {
	o.Name = v
}

// GetFailureCategory returns the FailureCategory field value
func (o *UpdateFailureCategoryProjectApiModel) GetFailureCategory() FailureCategory {
	if o == nil {
		var ret FailureCategory
		return ret
	}

	return o.FailureCategory
}

// GetFailureCategoryOk returns a tuple with the FailureCategory field value
// and a boolean to check if the value has been set.
func (o *UpdateFailureCategoryProjectApiModel) GetFailureCategoryOk() (*FailureCategory, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailureCategory, true
}

// SetFailureCategory sets field value
func (o *UpdateFailureCategoryProjectApiModel) SetFailureCategory(v FailureCategory) {
	o.FailureCategory = v
}

// GetFailureClassRegexes returns the FailureClassRegexes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateFailureCategoryProjectApiModel) GetFailureClassRegexes() []UpdateFailureClassRegexApiModel {
	if o == nil {
		var ret []UpdateFailureClassRegexApiModel
		return ret
	}
	return o.FailureClassRegexes
}

// GetFailureClassRegexesOk returns a tuple with the FailureClassRegexes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateFailureCategoryProjectApiModel) GetFailureClassRegexesOk() ([]UpdateFailureClassRegexApiModel, bool) {
	if o == nil || IsNil(o.FailureClassRegexes) {
		return nil, false
	}
	return o.FailureClassRegexes, true
}

// HasFailureClassRegexes returns a boolean if a field has been set.
func (o *UpdateFailureCategoryProjectApiModel) HasFailureClassRegexes() bool {
	if o != nil && !IsNil(o.FailureClassRegexes) {
		return true
	}

	return false
}

// SetFailureClassRegexes gets a reference to the given []UpdateFailureClassRegexApiModel and assigns it to the FailureClassRegexes field.
func (o *UpdateFailureCategoryProjectApiModel) SetFailureClassRegexes(v []UpdateFailureClassRegexApiModel) {
	o.FailureClassRegexes = v
}

func (o UpdateFailureCategoryProjectApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateFailureCategoryProjectApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["failureCategory"] = o.FailureCategory
	if o.FailureClassRegexes != nil {
		toSerialize["failureClassRegexes"] = o.FailureClassRegexes
	}
	return toSerialize, nil
}

func (o *UpdateFailureCategoryProjectApiModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"failureCategory",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateFailureCategoryProjectApiModel := _UpdateFailureCategoryProjectApiModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateFailureCategoryProjectApiModel)

	if err != nil {
		return err
	}

	*o = UpdateFailureCategoryProjectApiModel(varUpdateFailureCategoryProjectApiModel)

	return err
}

type NullableUpdateFailureCategoryProjectApiModel struct {
	value *UpdateFailureCategoryProjectApiModel
	isSet bool
}

func (v NullableUpdateFailureCategoryProjectApiModel) Get() *UpdateFailureCategoryProjectApiModel {
	return v.value
}

func (v *NullableUpdateFailureCategoryProjectApiModel) Set(val *UpdateFailureCategoryProjectApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFailureCategoryProjectApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFailureCategoryProjectApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFailureCategoryProjectApiModel(val *UpdateFailureCategoryProjectApiModel) *NullableUpdateFailureCategoryProjectApiModel {
	return &NullableUpdateFailureCategoryProjectApiModel{value: val, isSet: true}
}

func (v NullableUpdateFailureCategoryProjectApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFailureCategoryProjectApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


