/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetXlsxTestPointsByTestPlanApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetXlsxTestPointsByTestPlanApiModel{}

// GetXlsxTestPointsByTestPlanApiModel struct for GetXlsxTestPointsByTestPlanApiModel
type GetXlsxTestPointsByTestPlanApiModel struct {
	IncludeName bool `json:"includeName"`
	IncludeSection bool `json:"includeSection"`
	IncludePriority bool `json:"includePriority"`
	IncludeSourceType bool `json:"includeSourceType"`
	IncludeAutomated bool `json:"includeAutomated"`
	IncludeStatus bool `json:"includeStatus"`
	IncludeDuration bool `json:"includeDuration"`
	IncludeCreationDate bool `json:"includeCreationDate"`
	IncludeAuthor bool `json:"includeAuthor"`
	IncludeModificationDate bool `json:"includeModificationDate"`
	IncludeModifiedBy bool `json:"includeModifiedBy"`
	IncludeTags bool `json:"includeTags"`
	IncludeIterations bool `json:"includeIterations"`
	CustomAttributesIds []string `json:"customAttributesIds,omitempty"`
	Filter NullableTestPlanTestPointsSearchApiModel `json:"filter,omitempty"`
	Order []Order `json:"order"`
	// Deprecated
	ConfigurationIds []string `json:"configurationIds,omitempty"`
}

type _GetXlsxTestPointsByTestPlanApiModel GetXlsxTestPointsByTestPlanApiModel

// NewGetXlsxTestPointsByTestPlanApiModel instantiates a new GetXlsxTestPointsByTestPlanApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetXlsxTestPointsByTestPlanApiModel(includeName bool, includeSection bool, includePriority bool, includeSourceType bool, includeAutomated bool, includeStatus bool, includeDuration bool, includeCreationDate bool, includeAuthor bool, includeModificationDate bool, includeModifiedBy bool, includeTags bool, includeIterations bool, order []Order) *GetXlsxTestPointsByTestPlanApiModel {
	this := GetXlsxTestPointsByTestPlanApiModel{}
	this.IncludeName = includeName
	this.IncludeSection = includeSection
	this.IncludePriority = includePriority
	this.IncludeSourceType = includeSourceType
	this.IncludeAutomated = includeAutomated
	this.IncludeStatus = includeStatus
	this.IncludeDuration = includeDuration
	this.IncludeCreationDate = includeCreationDate
	this.IncludeAuthor = includeAuthor
	this.IncludeModificationDate = includeModificationDate
	this.IncludeModifiedBy = includeModifiedBy
	this.IncludeTags = includeTags
	this.IncludeIterations = includeIterations
	this.Order = order
	return &this
}

// NewGetXlsxTestPointsByTestPlanApiModelWithDefaults instantiates a new GetXlsxTestPointsByTestPlanApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetXlsxTestPointsByTestPlanApiModelWithDefaults() *GetXlsxTestPointsByTestPlanApiModel {
	this := GetXlsxTestPointsByTestPlanApiModel{}
	return &this
}

// GetIncludeName returns the IncludeName field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeName() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeName
}

// GetIncludeNameOk returns a tuple with the IncludeName field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeNameOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeName, true
}

// SetIncludeName sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeName(v bool) {
	o.IncludeName = v
}

// GetIncludeSection returns the IncludeSection field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeSection() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeSection
}

// GetIncludeSectionOk returns a tuple with the IncludeSection field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeSectionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeSection, true
}

// SetIncludeSection sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeSection(v bool) {
	o.IncludeSection = v
}

// GetIncludePriority returns the IncludePriority field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludePriority() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludePriority
}

// GetIncludePriorityOk returns a tuple with the IncludePriority field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludePriorityOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludePriority, true
}

// SetIncludePriority sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludePriority(v bool) {
	o.IncludePriority = v
}

// GetIncludeSourceType returns the IncludeSourceType field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeSourceType() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeSourceType
}

// GetIncludeSourceTypeOk returns a tuple with the IncludeSourceType field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeSourceTypeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeSourceType, true
}

// SetIncludeSourceType sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeSourceType(v bool) {
	o.IncludeSourceType = v
}

// GetIncludeAutomated returns the IncludeAutomated field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeAutomated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeAutomated
}

// GetIncludeAutomatedOk returns a tuple with the IncludeAutomated field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeAutomatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeAutomated, true
}

// SetIncludeAutomated sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeAutomated(v bool) {
	o.IncludeAutomated = v
}

// GetIncludeStatus returns the IncludeStatus field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeStatus
}

// GetIncludeStatusOk returns a tuple with the IncludeStatus field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeStatus, true
}

// SetIncludeStatus sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeStatus(v bool) {
	o.IncludeStatus = v
}

// GetIncludeDuration returns the IncludeDuration field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeDuration() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeDuration
}

// GetIncludeDurationOk returns a tuple with the IncludeDuration field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeDurationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeDuration, true
}

// SetIncludeDuration sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeDuration(v bool) {
	o.IncludeDuration = v
}

// GetIncludeCreationDate returns the IncludeCreationDate field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeCreationDate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeCreationDate
}

// GetIncludeCreationDateOk returns a tuple with the IncludeCreationDate field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeCreationDateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeCreationDate, true
}

// SetIncludeCreationDate sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeCreationDate(v bool) {
	o.IncludeCreationDate = v
}

// GetIncludeAuthor returns the IncludeAuthor field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeAuthor() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeAuthor
}

// GetIncludeAuthorOk returns a tuple with the IncludeAuthor field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeAuthorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeAuthor, true
}

// SetIncludeAuthor sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeAuthor(v bool) {
	o.IncludeAuthor = v
}

// GetIncludeModificationDate returns the IncludeModificationDate field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeModificationDate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeModificationDate
}

// GetIncludeModificationDateOk returns a tuple with the IncludeModificationDate field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeModificationDateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeModificationDate, true
}

// SetIncludeModificationDate sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeModificationDate(v bool) {
	o.IncludeModificationDate = v
}

// GetIncludeModifiedBy returns the IncludeModifiedBy field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeModifiedBy() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeModifiedBy
}

// GetIncludeModifiedByOk returns a tuple with the IncludeModifiedBy field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeModifiedByOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeModifiedBy, true
}

// SetIncludeModifiedBy sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeModifiedBy(v bool) {
	o.IncludeModifiedBy = v
}

// GetIncludeTags returns the IncludeTags field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeTags() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeTags
}

// GetIncludeTagsOk returns a tuple with the IncludeTags field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeTagsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeTags, true
}

// SetIncludeTags sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeTags(v bool) {
	o.IncludeTags = v
}

// GetIncludeIterations returns the IncludeIterations field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeIterations() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IncludeIterations
}

// GetIncludeIterationsOk returns a tuple with the IncludeIterations field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetIncludeIterationsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncludeIterations, true
}

// SetIncludeIterations sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetIncludeIterations(v bool) {
	o.IncludeIterations = v
}

// GetCustomAttributesIds returns the CustomAttributesIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetXlsxTestPointsByTestPlanApiModel) GetCustomAttributesIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.CustomAttributesIds
}

// GetCustomAttributesIdsOk returns a tuple with the CustomAttributesIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetXlsxTestPointsByTestPlanApiModel) GetCustomAttributesIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.CustomAttributesIds) {
		return nil, false
	}
	return o.CustomAttributesIds, true
}

// HasCustomAttributesIds returns a boolean if a field has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) HasCustomAttributesIds() bool {
	if o != nil && !IsNil(o.CustomAttributesIds) {
		return true
	}

	return false
}

// SetCustomAttributesIds gets a reference to the given []string and assigns it to the CustomAttributesIds field.
func (o *GetXlsxTestPointsByTestPlanApiModel) SetCustomAttributesIds(v []string) {
	o.CustomAttributesIds = v
}

// GetFilter returns the Filter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetXlsxTestPointsByTestPlanApiModel) GetFilter() TestPlanTestPointsSearchApiModel {
	if o == nil || IsNil(o.Filter.Get()) {
		var ret TestPlanTestPointsSearchApiModel
		return ret
	}
	return *o.Filter.Get()
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetXlsxTestPointsByTestPlanApiModel) GetFilterOk() (*TestPlanTestPointsSearchApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filter.Get(), o.Filter.IsSet()
}

// HasFilter returns a boolean if a field has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) HasFilter() bool {
	if o != nil && o.Filter.IsSet() {
		return true
	}

	return false
}

// SetFilter gets a reference to the given NullableTestPlanTestPointsSearchApiModel and assigns it to the Filter field.
func (o *GetXlsxTestPointsByTestPlanApiModel) SetFilter(v TestPlanTestPointsSearchApiModel) {
	o.Filter.Set(&v)
}
// SetFilterNil sets the value for Filter to be an explicit nil
func (o *GetXlsxTestPointsByTestPlanApiModel) SetFilterNil() {
	o.Filter.Set(nil)
}

// UnsetFilter ensures that no value is present for Filter, not even an explicit nil
func (o *GetXlsxTestPointsByTestPlanApiModel) UnsetFilter() {
	o.Filter.Unset()
}

// GetOrder returns the Order field value
func (o *GetXlsxTestPointsByTestPlanApiModel) GetOrder() []Order {
	if o == nil {
		var ret []Order
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) GetOrderOk() ([]Order, bool) {
	if o == nil {
		return nil, false
	}
	return o.Order, true
}

// SetOrder sets field value
func (o *GetXlsxTestPointsByTestPlanApiModel) SetOrder(v []Order) {
	o.Order = v
}

// GetConfigurationIds returns the ConfigurationIds field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *GetXlsxTestPointsByTestPlanApiModel) GetConfigurationIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ConfigurationIds
}

// GetConfigurationIdsOk returns a tuple with the ConfigurationIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *GetXlsxTestPointsByTestPlanApiModel) GetConfigurationIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ConfigurationIds) {
		return nil, false
	}
	return o.ConfigurationIds, true
}

// HasConfigurationIds returns a boolean if a field has been set.
func (o *GetXlsxTestPointsByTestPlanApiModel) HasConfigurationIds() bool {
	if o != nil && !IsNil(o.ConfigurationIds) {
		return true
	}

	return false
}

// SetConfigurationIds gets a reference to the given []string and assigns it to the ConfigurationIds field.
// Deprecated
func (o *GetXlsxTestPointsByTestPlanApiModel) SetConfigurationIds(v []string) {
	o.ConfigurationIds = v
}

func (o GetXlsxTestPointsByTestPlanApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetXlsxTestPointsByTestPlanApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["includeName"] = o.IncludeName
	toSerialize["includeSection"] = o.IncludeSection
	toSerialize["includePriority"] = o.IncludePriority
	toSerialize["includeSourceType"] = o.IncludeSourceType
	toSerialize["includeAutomated"] = o.IncludeAutomated
	toSerialize["includeStatus"] = o.IncludeStatus
	toSerialize["includeDuration"] = o.IncludeDuration
	toSerialize["includeCreationDate"] = o.IncludeCreationDate
	toSerialize["includeAuthor"] = o.IncludeAuthor
	toSerialize["includeModificationDate"] = o.IncludeModificationDate
	toSerialize["includeModifiedBy"] = o.IncludeModifiedBy
	toSerialize["includeTags"] = o.IncludeTags
	toSerialize["includeIterations"] = o.IncludeIterations
	if o.CustomAttributesIds != nil {
		toSerialize["customAttributesIds"] = o.CustomAttributesIds
	}
	if o.Filter.IsSet() {
		toSerialize["filter"] = o.Filter.Get()
	}
	toSerialize["order"] = o.Order
	if o.ConfigurationIds != nil {
		toSerialize["configurationIds"] = o.ConfigurationIds
	}
	return toSerialize, nil
}

func (o *GetXlsxTestPointsByTestPlanApiModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"includeName",
		"includeSection",
		"includePriority",
		"includeSourceType",
		"includeAutomated",
		"includeStatus",
		"includeDuration",
		"includeCreationDate",
		"includeAuthor",
		"includeModificationDate",
		"includeModifiedBy",
		"includeTags",
		"includeIterations",
		"order",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetXlsxTestPointsByTestPlanApiModel := _GetXlsxTestPointsByTestPlanApiModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetXlsxTestPointsByTestPlanApiModel)

	if err != nil {
		return err
	}

	*o = GetXlsxTestPointsByTestPlanApiModel(varGetXlsxTestPointsByTestPlanApiModel)

	return err
}

type NullableGetXlsxTestPointsByTestPlanApiModel struct {
	value *GetXlsxTestPointsByTestPlanApiModel
	isSet bool
}

func (v NullableGetXlsxTestPointsByTestPlanApiModel) Get() *GetXlsxTestPointsByTestPlanApiModel {
	return v.value
}

func (v *NullableGetXlsxTestPointsByTestPlanApiModel) Set(val *GetXlsxTestPointsByTestPlanApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGetXlsxTestPointsByTestPlanApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGetXlsxTestPointsByTestPlanApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetXlsxTestPointsByTestPlanApiModel(val *GetXlsxTestPointsByTestPlanApiModel) *NullableGetXlsxTestPointsByTestPlanApiModel {
	return &NullableGetXlsxTestPointsByTestPlanApiModel{value: val, isSet: true}
}

func (v NullableGetXlsxTestPointsByTestPlanApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetXlsxTestPointsByTestPlanApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


