/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateWorkItemApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWorkItemApiModel{}

// CreateWorkItemApiModel struct for CreateWorkItemApiModel
type CreateWorkItemApiModel struct {
	// Unique identifier of the project
	ProjectId string `json:"projectId"`
	// Unique identifier of the section within a project
	SectionId NullableString `json:"sectionId,omitempty"`
	// Name of the work item
	Name string `json:"name"`
	// Description of the work item
	Description NullableString `json:"description,omitempty"`
	// Type of entity associated with this work item
	EntityTypeName WorkItemEntityTypeApiModel `json:"entityTypeName"`
	// Duration of the work item in milliseconds
	Duration int32 `json:"duration"`
	// State of the work item
	State WorkItemStateApiModel `json:"state"`
	// Priority level of the work item
	Priority WorkItemPriorityApiModel `json:"priority"`
	// Set of custom attributes associated with the work item
	Attributes map[string]interface{} `json:"attributes"`
	// Set of tags applied to the work item
	Tags []TagModel `json:"tags"`
	// Set of precondition steps that need to be executed before starting the main steps
	PreconditionSteps []CreateStepApiModel `json:"preconditionSteps"`
	// Main steps or actions defined for the work item
	Steps []CreateStepApiModel `json:"steps"`
	// Set of postcondition steps that are executed after completing the main steps
	PostconditionSteps []CreateStepApiModel `json:"postconditionSteps"`
	// Associated iterations linked to the work item
	Iterations []AssignIterationApiModel `json:"iterations,omitempty"`
	// Automated tests associated with the work item
	AutoTests []AutoTestIdModel `json:"autoTests,omitempty"`
	// Files attached to the work item
	Attachments []AssignAttachmentApiModel `json:"attachments,omitempty"`
	// Set of links related to the work item
	Links []CreateLinkApiModel `json:"links"`
}

type _CreateWorkItemApiModel CreateWorkItemApiModel

// NewCreateWorkItemApiModel instantiates a new CreateWorkItemApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWorkItemApiModel(projectId string, name string, entityTypeName WorkItemEntityTypeApiModel, duration int32, state WorkItemStateApiModel, priority WorkItemPriorityApiModel, attributes map[string]interface{}, tags []TagModel, preconditionSteps []CreateStepApiModel, steps []CreateStepApiModel, postconditionSteps []CreateStepApiModel, links []CreateLinkApiModel) *CreateWorkItemApiModel {
	this := CreateWorkItemApiModel{}
	this.ProjectId = projectId
	this.Name = name
	this.EntityTypeName = entityTypeName
	this.Duration = duration
	this.State = state
	this.Priority = priority
	this.Attributes = attributes
	this.Tags = tags
	this.PreconditionSteps = preconditionSteps
	this.Steps = steps
	this.PostconditionSteps = postconditionSteps
	this.Links = links
	return &this
}

// NewCreateWorkItemApiModelWithDefaults instantiates a new CreateWorkItemApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWorkItemApiModelWithDefaults() *CreateWorkItemApiModel {
	this := CreateWorkItemApiModel{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *CreateWorkItemApiModel) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *CreateWorkItemApiModel) SetProjectId(v string) {
	o.ProjectId = v
}

// GetSectionId returns the SectionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkItemApiModel) GetSectionId() string {
	if o == nil || IsNil(o.SectionId.Get()) {
		var ret string
		return ret
	}
	return *o.SectionId.Get()
}

// GetSectionIdOk returns a tuple with the SectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkItemApiModel) GetSectionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SectionId.Get(), o.SectionId.IsSet()
}

// HasSectionId returns a boolean if a field has been set.
func (o *CreateWorkItemApiModel) HasSectionId() bool {
	if o != nil && o.SectionId.IsSet() {
		return true
	}

	return false
}

// SetSectionId gets a reference to the given NullableString and assigns it to the SectionId field.
func (o *CreateWorkItemApiModel) SetSectionId(v string) {
	o.SectionId.Set(&v)
}
// SetSectionIdNil sets the value for SectionId to be an explicit nil
func (o *CreateWorkItemApiModel) SetSectionIdNil() {
	o.SectionId.Set(nil)
}

// UnsetSectionId ensures that no value is present for SectionId, not even an explicit nil
func (o *CreateWorkItemApiModel) UnsetSectionId() {
	o.SectionId.Unset()
}

// GetName returns the Name field value
func (o *CreateWorkItemApiModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateWorkItemApiModel) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkItemApiModel) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkItemApiModel) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateWorkItemApiModel) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CreateWorkItemApiModel) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CreateWorkItemApiModel) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CreateWorkItemApiModel) UnsetDescription() {
	o.Description.Unset()
}

// GetEntityTypeName returns the EntityTypeName field value
func (o *CreateWorkItemApiModel) GetEntityTypeName() WorkItemEntityTypeApiModel {
	if o == nil {
		var ret WorkItemEntityTypeApiModel
		return ret
	}

	return o.EntityTypeName
}

// GetEntityTypeNameOk returns a tuple with the EntityTypeName field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetEntityTypeNameOk() (*WorkItemEntityTypeApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityTypeName, true
}

// SetEntityTypeName sets field value
func (o *CreateWorkItemApiModel) SetEntityTypeName(v WorkItemEntityTypeApiModel) {
	o.EntityTypeName = v
}

// GetDuration returns the Duration field value
func (o *CreateWorkItemApiModel) GetDuration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetDurationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *CreateWorkItemApiModel) SetDuration(v int32) {
	o.Duration = v
}

// GetState returns the State field value
func (o *CreateWorkItemApiModel) GetState() WorkItemStateApiModel {
	if o == nil {
		var ret WorkItemStateApiModel
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetStateOk() (*WorkItemStateApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *CreateWorkItemApiModel) SetState(v WorkItemStateApiModel) {
	o.State = v
}

// GetPriority returns the Priority field value
func (o *CreateWorkItemApiModel) GetPriority() WorkItemPriorityApiModel {
	if o == nil {
		var ret WorkItemPriorityApiModel
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetPriorityOk() (*WorkItemPriorityApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *CreateWorkItemApiModel) SetPriority(v WorkItemPriorityApiModel) {
	o.Priority = v
}

// GetAttributes returns the Attributes field value
func (o *CreateWorkItemApiModel) GetAttributes() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateWorkItemApiModel) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

// GetTags returns the Tags field value
func (o *CreateWorkItemApiModel) GetTags() []TagModel {
	if o == nil {
		var ret []TagModel
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetTagsOk() ([]TagModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *CreateWorkItemApiModel) SetTags(v []TagModel) {
	o.Tags = v
}

// GetPreconditionSteps returns the PreconditionSteps field value
func (o *CreateWorkItemApiModel) GetPreconditionSteps() []CreateStepApiModel {
	if o == nil {
		var ret []CreateStepApiModel
		return ret
	}

	return o.PreconditionSteps
}

// GetPreconditionStepsOk returns a tuple with the PreconditionSteps field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetPreconditionStepsOk() ([]CreateStepApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreconditionSteps, true
}

// SetPreconditionSteps sets field value
func (o *CreateWorkItemApiModel) SetPreconditionSteps(v []CreateStepApiModel) {
	o.PreconditionSteps = v
}

// GetSteps returns the Steps field value
func (o *CreateWorkItemApiModel) GetSteps() []CreateStepApiModel {
	if o == nil {
		var ret []CreateStepApiModel
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetStepsOk() ([]CreateStepApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Steps, true
}

// SetSteps sets field value
func (o *CreateWorkItemApiModel) SetSteps(v []CreateStepApiModel) {
	o.Steps = v
}

// GetPostconditionSteps returns the PostconditionSteps field value
func (o *CreateWorkItemApiModel) GetPostconditionSteps() []CreateStepApiModel {
	if o == nil {
		var ret []CreateStepApiModel
		return ret
	}

	return o.PostconditionSteps
}

// GetPostconditionStepsOk returns a tuple with the PostconditionSteps field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetPostconditionStepsOk() ([]CreateStepApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.PostconditionSteps, true
}

// SetPostconditionSteps sets field value
func (o *CreateWorkItemApiModel) SetPostconditionSteps(v []CreateStepApiModel) {
	o.PostconditionSteps = v
}

// GetIterations returns the Iterations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkItemApiModel) GetIterations() []AssignIterationApiModel {
	if o == nil {
		var ret []AssignIterationApiModel
		return ret
	}
	return o.Iterations
}

// GetIterationsOk returns a tuple with the Iterations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkItemApiModel) GetIterationsOk() ([]AssignIterationApiModel, bool) {
	if o == nil || IsNil(o.Iterations) {
		return nil, false
	}
	return o.Iterations, true
}

// HasIterations returns a boolean if a field has been set.
func (o *CreateWorkItemApiModel) HasIterations() bool {
	if o != nil && !IsNil(o.Iterations) {
		return true
	}

	return false
}

// SetIterations gets a reference to the given []AssignIterationApiModel and assigns it to the Iterations field.
func (o *CreateWorkItemApiModel) SetIterations(v []AssignIterationApiModel) {
	o.Iterations = v
}

// GetAutoTests returns the AutoTests field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkItemApiModel) GetAutoTests() []AutoTestIdModel {
	if o == nil {
		var ret []AutoTestIdModel
		return ret
	}
	return o.AutoTests
}

// GetAutoTestsOk returns a tuple with the AutoTests field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkItemApiModel) GetAutoTestsOk() ([]AutoTestIdModel, bool) {
	if o == nil || IsNil(o.AutoTests) {
		return nil, false
	}
	return o.AutoTests, true
}

// HasAutoTests returns a boolean if a field has been set.
func (o *CreateWorkItemApiModel) HasAutoTests() bool {
	if o != nil && !IsNil(o.AutoTests) {
		return true
	}

	return false
}

// SetAutoTests gets a reference to the given []AutoTestIdModel and assigns it to the AutoTests field.
func (o *CreateWorkItemApiModel) SetAutoTests(v []AutoTestIdModel) {
	o.AutoTests = v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateWorkItemApiModel) GetAttachments() []AssignAttachmentApiModel {
	if o == nil {
		var ret []AssignAttachmentApiModel
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateWorkItemApiModel) GetAttachmentsOk() ([]AssignAttachmentApiModel, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *CreateWorkItemApiModel) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []AssignAttachmentApiModel and assigns it to the Attachments field.
func (o *CreateWorkItemApiModel) SetAttachments(v []AssignAttachmentApiModel) {
	o.Attachments = v
}

// GetLinks returns the Links field value
func (o *CreateWorkItemApiModel) GetLinks() []CreateLinkApiModel {
	if o == nil {
		var ret []CreateLinkApiModel
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *CreateWorkItemApiModel) GetLinksOk() ([]CreateLinkApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Links, true
}

// SetLinks sets field value
func (o *CreateWorkItemApiModel) SetLinks(v []CreateLinkApiModel) {
	o.Links = v
}

func (o CreateWorkItemApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWorkItemApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectId"] = o.ProjectId
	if o.SectionId.IsSet() {
		toSerialize["sectionId"] = o.SectionId.Get()
	}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["entityTypeName"] = o.EntityTypeName
	toSerialize["duration"] = o.Duration
	toSerialize["state"] = o.State
	toSerialize["priority"] = o.Priority
	toSerialize["attributes"] = o.Attributes
	toSerialize["tags"] = o.Tags
	toSerialize["preconditionSteps"] = o.PreconditionSteps
	toSerialize["steps"] = o.Steps
	toSerialize["postconditionSteps"] = o.PostconditionSteps
	if o.Iterations != nil {
		toSerialize["iterations"] = o.Iterations
	}
	if o.AutoTests != nil {
		toSerialize["autoTests"] = o.AutoTests
	}
	if o.Attachments != nil {
		toSerialize["attachments"] = o.Attachments
	}
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *CreateWorkItemApiModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projectId",
		"name",
		"entityTypeName",
		"duration",
		"state",
		"priority",
		"attributes",
		"tags",
		"preconditionSteps",
		"steps",
		"postconditionSteps",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateWorkItemApiModel := _CreateWorkItemApiModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateWorkItemApiModel)

	if err != nil {
		return err
	}

	*o = CreateWorkItemApiModel(varCreateWorkItemApiModel)

	return err
}

type NullableCreateWorkItemApiModel struct {
	value *CreateWorkItemApiModel
	isSet bool
}

func (v NullableCreateWorkItemApiModel) Get() *CreateWorkItemApiModel {
	return v.value
}

func (v *NullableCreateWorkItemApiModel) Set(val *CreateWorkItemApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWorkItemApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWorkItemApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWorkItemApiModel(val *CreateWorkItemApiModel) *NullableCreateWorkItemApiModel {
	return &NullableCreateWorkItemApiModel{value: val, isSet: true}
}

func (v NullableCreateWorkItemApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWorkItemApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


