/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
)

// checks if the WorkItemChangedFieldsViewModelGlobalId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkItemChangedFieldsViewModelGlobalId{}

// WorkItemChangedFieldsViewModelGlobalId struct for WorkItemChangedFieldsViewModelGlobalId
type WorkItemChangedFieldsViewModelGlobalId struct {
	OldValue int64 `json:"oldValue"`
	NewValue int64 `json:"newValue"`
}

// NewWorkItemChangedFieldsViewModelGlobalId instantiates a new WorkItemChangedFieldsViewModelGlobalId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkItemChangedFieldsViewModelGlobalId(oldValue int64, newValue int64) *WorkItemChangedFieldsViewModelGlobalId {
	this := WorkItemChangedFieldsViewModelGlobalId{}
	this.OldValue = oldValue
	this.NewValue = newValue
	return &this
}

// NewWorkItemChangedFieldsViewModelGlobalIdWithDefaults instantiates a new WorkItemChangedFieldsViewModelGlobalId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkItemChangedFieldsViewModelGlobalIdWithDefaults() *WorkItemChangedFieldsViewModelGlobalId {
	this := WorkItemChangedFieldsViewModelGlobalId{}
	return &this
}

// GetOldValue returns the OldValue field value
func (o *WorkItemChangedFieldsViewModelGlobalId) GetOldValue() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OldValue
}

// GetOldValueOk returns a tuple with the OldValue field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModelGlobalId) GetOldValueOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OldValue, true
}

// SetOldValue sets field value
func (o *WorkItemChangedFieldsViewModelGlobalId) SetOldValue(v int64) {
	o.OldValue = v
}

// GetNewValue returns the NewValue field value
func (o *WorkItemChangedFieldsViewModelGlobalId) GetNewValue() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NewValue
}

// GetNewValueOk returns a tuple with the NewValue field value
// and a boolean to check if the value has been set.
func (o *WorkItemChangedFieldsViewModelGlobalId) GetNewValueOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewValue, true
}

// SetNewValue sets field value
func (o *WorkItemChangedFieldsViewModelGlobalId) SetNewValue(v int64) {
	o.NewValue = v
}

func (o WorkItemChangedFieldsViewModelGlobalId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkItemChangedFieldsViewModelGlobalId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["oldValue"] = o.OldValue
	toSerialize["newValue"] = o.NewValue
	return toSerialize, nil
}

type NullableWorkItemChangedFieldsViewModelGlobalId struct {
	value *WorkItemChangedFieldsViewModelGlobalId
	isSet bool
}

func (v NullableWorkItemChangedFieldsViewModelGlobalId) Get() *WorkItemChangedFieldsViewModelGlobalId {
	return v.value
}

func (v *NullableWorkItemChangedFieldsViewModelGlobalId) Set(val *WorkItemChangedFieldsViewModelGlobalId) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkItemChangedFieldsViewModelGlobalId) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkItemChangedFieldsViewModelGlobalId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkItemChangedFieldsViewModelGlobalId(val *WorkItemChangedFieldsViewModelGlobalId) *NullableWorkItemChangedFieldsViewModelGlobalId {
	return &NullableWorkItemChangedFieldsViewModelGlobalId{value: val, isSet: true}
}

func (v NullableWorkItemChangedFieldsViewModelGlobalId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkItemChangedFieldsViewModelGlobalId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


