/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"fmt"
)

// LayerSource the model 'LayerSource'
type LayerSource string

// List of LayerSource
const (
	LAYERSOURCE_MANUAL LayerSource = "Manual"
	LAYERSOURCE_REPORT LayerSource = "Report"
	LAYERSOURCE_RUN LayerSource = "Run"
	LAYERSOURCE_RULE LayerSource = "Rule"
)

// All allowed values of LayerSource enum
var AllowedLayerSourceEnumValues = []LayerSource{
	"Manual",
	"Report",
	"Run",
	"Rule",
}

func (v *LayerSource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LayerSource(value)
	for _, existing := range AllowedLayerSourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LayerSource", value)
}

// NewLayerSourceFromValue returns a pointer to a valid LayerSource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLayerSourceFromValue(v string) (*LayerSource, error) {
	ev := LayerSource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LayerSource: valid values are %v", v, AllowedLayerSourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LayerSource) IsValid() bool {
	for _, existing := range AllowedLayerSourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LayerSource value
func (v LayerSource) Ptr() *LayerSource {
	return &v
}

type NullableLayerSource struct {
	value *LayerSource
	isSet bool
}

func (v NullableLayerSource) Get() *LayerSource {
	return v.value
}

func (v *NullableLayerSource) Set(val *LayerSource) {
	v.value = val
	v.isSet = true
}

func (v NullableLayerSource) IsSet() bool {
	return v.isSet
}

func (v *NullableLayerSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLayerSource(val *LayerSource) *NullableLayerSource {
	return &NullableLayerSource{value: val, isSet: true}
}

func (v NullableLayerSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLayerSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

