/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"fmt"
)

// WebHookEventTypeModel the model 'WebHookEventTypeModel'
type WebHookEventTypeModel string

// List of WebHookEventTypeModel
const (
	WEBHOOKEVENTTYPEMODEL_AUTOMATED_TEST_RUN_CREATED WebHookEventTypeModel = "AutomatedTestRunCreated"
	WEBHOOKEVENTTYPEMODEL_TEST_PLANS_STATUS_CHANGED WebHookEventTypeModel = "TestPlansStatusChanged"
	WEBHOOKEVENTTYPEMODEL_TEST_RUN_STOPPED WebHookEventTypeModel = "TestRunStopped"
	WEBHOOKEVENTTYPEMODEL_TEST_POINT_ASSIGNED WebHookEventTypeModel = "TestPointAssigned"
	WEBHOOKEVENTTYPEMODEL_TEST_RESULT_JIRA_ISSUE_CREATED WebHookEventTypeModel = "TestResultJiraIssueCreated"
	WEBHOOKEVENTTYPEMODEL_AUTO_TEST_FINISHED WebHookEventTypeModel = "AutoTestFinished"
	WEBHOOKEVENTTYPEMODEL_USER_MENTIONED_IN_COMMENT WebHookEventTypeModel = "UserMentionedInComment"
	WEBHOOKEVENTTYPEMODEL_USER_SELECTED_IN_WORK_ITEM_ATTRIBUTE WebHookEventTypeModel = "UserSelectedInWorkItemAttribute"
	WEBHOOKEVENTTYPEMODEL_ALL_TEST_POINTS_FINISHED WebHookEventTypeModel = "AllTestPointsFinished"
	WEBHOOKEVENTTYPEMODEL_ALL_AUTO_TESTS_FINISHED WebHookEventTypeModel = "AllAutoTestsFinished"
	WEBHOOKEVENTTYPEMODEL_AUTO_TEST_CHANGED WebHookEventTypeModel = "AutoTestChanged"
	WEBHOOKEVENTTYPEMODEL_WORK_ITEM_AUTO_TEST_RELATION_CHANGED WebHookEventTypeModel = "WorkItemAutoTestRelationChanged"
	WEBHOOKEVENTTYPEMODEL_WORK_ITEM_ATTRIBUTE_CHANGED WebHookEventTypeModel = "WorkItemAttributeChanged"
	WEBHOOKEVENTTYPEMODEL_WORK_ITEM_CHANGED WebHookEventTypeModel = "WorkItemChanged"
	WEBHOOKEVENTTYPEMODEL_CONFIGURATION_CHANGED WebHookEventTypeModel = "ConfigurationChanged"
)

// All allowed values of WebHookEventTypeModel enum
var AllowedWebHookEventTypeModelEnumValues = []WebHookEventTypeModel{
	"AutomatedTestRunCreated",
	"TestPlansStatusChanged",
	"TestRunStopped",
	"TestPointAssigned",
	"TestResultJiraIssueCreated",
	"AutoTestFinished",
	"UserMentionedInComment",
	"UserSelectedInWorkItemAttribute",
	"AllTestPointsFinished",
	"AllAutoTestsFinished",
	"AutoTestChanged",
	"WorkItemAutoTestRelationChanged",
	"WorkItemAttributeChanged",
	"WorkItemChanged",
	"ConfigurationChanged",
}

func (v *WebHookEventTypeModel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WebHookEventTypeModel(value)
	for _, existing := range AllowedWebHookEventTypeModelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WebHookEventTypeModel", value)
}

// NewWebHookEventTypeModelFromValue returns a pointer to a valid WebHookEventTypeModel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWebHookEventTypeModelFromValue(v string) (*WebHookEventTypeModel, error) {
	ev := WebHookEventTypeModel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WebHookEventTypeModel: valid values are %v", v, AllowedWebHookEventTypeModelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WebHookEventTypeModel) IsValid() bool {
	for _, existing := range AllowedWebHookEventTypeModelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WebHookEventTypeModel value
func (v WebHookEventTypeModel) Ptr() *WebHookEventTypeModel {
	return &v
}

type NullableWebHookEventTypeModel struct {
	value *WebHookEventTypeModel
	isSet bool
}

func (v NullableWebHookEventTypeModel) Get() *WebHookEventTypeModel {
	return v.value
}

func (v *NullableWebHookEventTypeModel) Set(val *WebHookEventTypeModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWebHookEventTypeModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWebHookEventTypeModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebHookEventTypeModel(val *WebHookEventTypeModel) *NullableWebHookEventTypeModel {
	return &NullableWebHookEventTypeModel{value: val, isSet: true}
}

func (v NullableWebHookEventTypeModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebHookEventTypeModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

