/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"fmt"
)

// WorkItemPriorityApiModel the model 'WorkItemPriorityApiModel'
type WorkItemPriorityApiModel string

// List of WorkItemPriorityApiModel
const (
	WORKITEMPRIORITYAPIMODEL_LOWEST WorkItemPriorityApiModel = "Lowest"
	WORKITEMPRIORITYAPIMODEL_LOW WorkItemPriorityApiModel = "Low"
	WORKITEMPRIORITYAPIMODEL_MEDIUM WorkItemPriorityApiModel = "Medium"
	WORKITEMPRIORITYAPIMODEL_HIGH WorkItemPriorityApiModel = "High"
	WORKITEMPRIORITYAPIMODEL_HIGHEST WorkItemPriorityApiModel = "Highest"
)

// All allowed values of WorkItemPriorityApiModel enum
var AllowedWorkItemPriorityApiModelEnumValues = []WorkItemPriorityApiModel{
	"Lowest",
	"Low",
	"Medium",
	"High",
	"Highest",
}

func (v *WorkItemPriorityApiModel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WorkItemPriorityApiModel(value)
	for _, existing := range AllowedWorkItemPriorityApiModelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WorkItemPriorityApiModel", value)
}

// NewWorkItemPriorityApiModelFromValue returns a pointer to a valid WorkItemPriorityApiModel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWorkItemPriorityApiModelFromValue(v string) (*WorkItemPriorityApiModel, error) {
	ev := WorkItemPriorityApiModel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WorkItemPriorityApiModel: valid values are %v", v, AllowedWorkItemPriorityApiModelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WorkItemPriorityApiModel) IsValid() bool {
	for _, existing := range AllowedWorkItemPriorityApiModelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WorkItemPriorityApiModel value
func (v WorkItemPriorityApiModel) Ptr() *WorkItemPriorityApiModel {
	return &v
}

type NullableWorkItemPriorityApiModel struct {
	value *WorkItemPriorityApiModel
	isSet bool
}

func (v NullableWorkItemPriorityApiModel) Get() *WorkItemPriorityApiModel {
	return v.value
}

func (v *NullableWorkItemPriorityApiModel) Set(val *WorkItemPriorityApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkItemPriorityApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkItemPriorityApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkItemPriorityApiModel(val *WorkItemPriorityApiModel) *NullableWorkItemPriorityApiModel {
	return &NullableWorkItemPriorityApiModel{value: val, isSet: true}
}

func (v NullableWorkItemPriorityApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkItemPriorityApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

