/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExternalIssueApiFieldSuggestionCountReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalIssueApiFieldSuggestionCountReply{}

// ExternalIssueApiFieldSuggestionCountReply struct for ExternalIssueApiFieldSuggestionCountReply
type ExternalIssueApiFieldSuggestionCountReply struct {
	TotalCount int32 `json:"totalCount"`
}

type _ExternalIssueApiFieldSuggestionCountReply ExternalIssueApiFieldSuggestionCountReply

// NewExternalIssueApiFieldSuggestionCountReply instantiates a new ExternalIssueApiFieldSuggestionCountReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalIssueApiFieldSuggestionCountReply(totalCount int32) *ExternalIssueApiFieldSuggestionCountReply {
	this := ExternalIssueApiFieldSuggestionCountReply{}
	this.TotalCount = totalCount
	return &this
}

// NewExternalIssueApiFieldSuggestionCountReplyWithDefaults instantiates a new ExternalIssueApiFieldSuggestionCountReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalIssueApiFieldSuggestionCountReplyWithDefaults() *ExternalIssueApiFieldSuggestionCountReply {
	this := ExternalIssueApiFieldSuggestionCountReply{}
	return &this
}

// GetTotalCount returns the TotalCount field value
func (o *ExternalIssueApiFieldSuggestionCountReply) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *ExternalIssueApiFieldSuggestionCountReply) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *ExternalIssueApiFieldSuggestionCountReply) SetTotalCount(v int32) {
	o.TotalCount = v
}

func (o ExternalIssueApiFieldSuggestionCountReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalIssueApiFieldSuggestionCountReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["totalCount"] = o.TotalCount
	return toSerialize, nil
}

func (o *ExternalIssueApiFieldSuggestionCountReply) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"totalCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExternalIssueApiFieldSuggestionCountReply := _ExternalIssueApiFieldSuggestionCountReply{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExternalIssueApiFieldSuggestionCountReply)

	if err != nil {
		return err
	}

	*o = ExternalIssueApiFieldSuggestionCountReply(varExternalIssueApiFieldSuggestionCountReply)

	return err
}

type NullableExternalIssueApiFieldSuggestionCountReply struct {
	value *ExternalIssueApiFieldSuggestionCountReply
	isSet bool
}

func (v NullableExternalIssueApiFieldSuggestionCountReply) Get() *ExternalIssueApiFieldSuggestionCountReply {
	return v.value
}

func (v *NullableExternalIssueApiFieldSuggestionCountReply) Set(val *ExternalIssueApiFieldSuggestionCountReply) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalIssueApiFieldSuggestionCountReply) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalIssueApiFieldSuggestionCountReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalIssueApiFieldSuggestionCountReply(val *ExternalIssueApiFieldSuggestionCountReply) *NullableExternalIssueApiFieldSuggestionCountReply {
	return &NullableExternalIssueApiFieldSuggestionCountReply{value: val, isSet: true}
}

func (v NullableExternalIssueApiFieldSuggestionCountReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalIssueApiFieldSuggestionCountReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


