/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateTagApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTagApiModel{}

// UpdateTagApiModel struct for UpdateTagApiModel
type UpdateTagApiModel struct {
	// Name of the tag
	Name string `json:"name"`
}

type _UpdateTagApiModel UpdateTagApiModel

// NewUpdateTagApiModel instantiates a new UpdateTagApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTagApiModel(name string) *UpdateTagApiModel {
	this := UpdateTagApiModel{}
	this.Name = name
	return &this
}

// NewUpdateTagApiModelWithDefaults instantiates a new UpdateTagApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTagApiModelWithDefaults() *UpdateTagApiModel {
	this := UpdateTagApiModel{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateTagApiModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateTagApiModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateTagApiModel) SetName(v string) {
	o.Name = v
}

func (o UpdateTagApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTagApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *UpdateTagApiModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTagApiModel := _UpdateTagApiModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateTagApiModel)

	if err != nil {
		return err
	}

	*o = UpdateTagApiModel(varUpdateTagApiModel)

	return err
}

type NullableUpdateTagApiModel struct {
	value *UpdateTagApiModel
	isSet bool
}

func (v NullableUpdateTagApiModel) Get() *UpdateTagApiModel {
	return v.value
}

func (v *NullableUpdateTagApiModel) Set(val *UpdateTagApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTagApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTagApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTagApiModel(val *UpdateTagApiModel) *NullableUpdateTagApiModel {
	return &NullableUpdateTagApiModel{value: val, isSet: true}
}

func (v NullableUpdateTagApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTagApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


