/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tmsclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AutoTestFlakyBulkApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoTestFlakyBulkApiModel{}

// AutoTestFlakyBulkApiModel struct for AutoTestFlakyBulkApiModel
type AutoTestFlakyBulkApiModel struct {
	AutoTestSelect AutoTestSelectApiModel `json:"autoTestSelect"`
	// Are autotests flaky
	Value bool `json:"value"`
}

type _AutoTestFlakyBulkApiModel AutoTestFlakyBulkApiModel

// NewAutoTestFlakyBulkApiModel instantiates a new AutoTestFlakyBulkApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoTestFlakyBulkApiModel(autoTestSelect AutoTestSelectApiModel, value bool) *AutoTestFlakyBulkApiModel {
	this := AutoTestFlakyBulkApiModel{}
	this.AutoTestSelect = autoTestSelect
	this.Value = value
	return &this
}

// NewAutoTestFlakyBulkApiModelWithDefaults instantiates a new AutoTestFlakyBulkApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoTestFlakyBulkApiModelWithDefaults() *AutoTestFlakyBulkApiModel {
	this := AutoTestFlakyBulkApiModel{}
	return &this
}

// GetAutoTestSelect returns the AutoTestSelect field value
func (o *AutoTestFlakyBulkApiModel) GetAutoTestSelect() AutoTestSelectApiModel {
	if o == nil {
		var ret AutoTestSelectApiModel
		return ret
	}

	return o.AutoTestSelect
}

// GetAutoTestSelectOk returns a tuple with the AutoTestSelect field value
// and a boolean to check if the value has been set.
func (o *AutoTestFlakyBulkApiModel) GetAutoTestSelectOk() (*AutoTestSelectApiModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutoTestSelect, true
}

// SetAutoTestSelect sets field value
func (o *AutoTestFlakyBulkApiModel) SetAutoTestSelect(v AutoTestSelectApiModel) {
	o.AutoTestSelect = v
}

// GetValue returns the Value field value
func (o *AutoTestFlakyBulkApiModel) GetValue() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *AutoTestFlakyBulkApiModel) GetValueOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *AutoTestFlakyBulkApiModel) SetValue(v bool) {
	o.Value = v
}

func (o AutoTestFlakyBulkApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoTestFlakyBulkApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["autoTestSelect"] = o.AutoTestSelect
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *AutoTestFlakyBulkApiModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"autoTestSelect",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAutoTestFlakyBulkApiModel := _AutoTestFlakyBulkApiModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAutoTestFlakyBulkApiModel)

	if err != nil {
		return err
	}

	*o = AutoTestFlakyBulkApiModel(varAutoTestFlakyBulkApiModel)

	return err
}

type NullableAutoTestFlakyBulkApiModel struct {
	value *AutoTestFlakyBulkApiModel
	isSet bool
}

func (v NullableAutoTestFlakyBulkApiModel) Get() *AutoTestFlakyBulkApiModel {
	return v.value
}

func (v *NullableAutoTestFlakyBulkApiModel) Set(val *AutoTestFlakyBulkApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoTestFlakyBulkApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoTestFlakyBulkApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoTestFlakyBulkApiModel(val *AutoTestFlakyBulkApiModel) *NullableAutoTestFlakyBulkApiModel {
	return &NullableAutoTestFlakyBulkApiModel{value: val, isSet: true}
}

func (v NullableAutoTestFlakyBulkApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoTestFlakyBulkApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


